import {ExchangeNote} from "@/components/i18n/Regional";

import {PriceText} from "@/components/i18n/Regional";
import Link from 'next/link';
import { BlogHeader, BlogFooter } from "@/locales/fr/components/BlogChrome";
import { Cases, DiagnosticCTA, FAQ, Team } from "@/locales/fr/components/Commercial";
import ScrollReveal from "@/locales/fr/components/ScrollReveal";
import { pageMetadata } from "@/locales/fr/lib/metadata";
export const metadata = pageMetadata({title:"Google + Site + SEO pour les entreprises",description:"Présence numérique avec site professionnel, maintenance et SEO. Forfait annuel unique de R$ 597,00, payable par Pix, carte ou boleto, avec les mêmes services Google, site et SEO.",alternates:{canonical:"/fr"}});
const pillars=[
  {name:'Google',title:"Profil d’entreprise Google et présence locale.",body:"Nous organisons et optimisons le Profil d’entreprise Google, lorsque l’entreprise est éligible, avec des informations cohérentes pour les recherches locales.",items:["Configuration et informations de l’entreprise","Optimisations pour les recherches locales","Améliorations continues"],href:"/fr/google-meu-negocio"},
  {name:'Site',title:"Création de sites professionnels.",body:"Nous créons et maintenons un site professionnel qui présente votre entreprise, inspire confiance et facilite le contact.",items:["Création du site et du domaine","Hébergement et mises à jour","Support continu"],href:"/fr/sites"},
  {name:'SEO',title:"SEO local et structure pour les recherches.",body:"Nous travaillons sur la structure et les pages du site pour que les moteurs de recherche comprennent mieux votre entreprise.",items:["Structure technique SEO","Optimisation des pages","Suivi et améliorations"],href:"/fr/seo"}
];
export default function Home(){return <><BlogHeader transparent/><main id="conteudo" tabIndex={-1} className="rv"><ScrollReveal/>
<section className="rv-hero"><video className="rv-hero-video" autoPlay muted loop playsInline preload="metadata" poster="/hero/ravyt-poster-20260927.webp" aria-hidden="true"><source src="/hero-video-20260927" type="video/mp4" /></video><div className="rv-hero-shade" aria-hidden="true"/><div className="shell rv-hero-inner"><p className="rv-label">Google • Site • SEO</p><h1> Google + Site + SEO pour les entreprises <em>  dans tout le Brésil. </em></h1><p className="rv-lead"> Votre entreprise doit être trouvée lorsque les clients font une recherche. Nous créons votre site et travaillons votre présence sur Google pour transformer les recherches en opportunités. </p><div className="rv-actions"><DiagnosticCTA/><a href="#como-funciona"> Comprendre comment cela fonctionne ↓ </a></div><p className="rv-hero-note"><PriceText> Forfait annuel unique : R$ 597,00 · Pix, carte ou boleto </PriceText></p></div><div className="shell rv-hero-bottom"><span> Être trouvée est le début. </span><span> Être choisie est l’étape suivante. </span></div></section>
<section className="rv-section rv-problem" data-reveal><div className="shell"><p className="rv-label"> La demande existe déjà </p><h2> Quand quelqu’un recherche ce que vous proposez, trouve-t-il votre entreprise <em>  ou votre concurrent ? </em></h2><p className="rv-intro"> Être sur Internet ne signifie pas être trouvé. Votre entreprise doit apparaître dans les recherches, inspirer confiance et offrir au client un moyen simple de vous contacter. </p><ol className="rv-path"><li> Recherche </li><li> Trouve </li><li> Fait confiance </li><li> Prend contact </li></ol></div></section>
<section className="rv-section rv-dark" data-reveal><div className="shell"><p className="rv-label"> La solution Ravyt </p><h2> Une structure complète pour votre entreprise <em>  se développer sur Google. </em></h2><p className="rv-intro"> Nous réunissons présence locale, site professionnel et SEO dans une stratégie unique pour construire et maintenir une présence numérique plus forte pour votre entreprise. </p></div></section>
<section className="rv-section rv-services" id="servicos"><div className="shell"><p className="rv-label" data-reveal> Trois piliers. Une offre. </p><h2 data-reveal>Google + Site + SEO.</h2><div className="rv-pillars">{<PriceText>{pillars.map((p,i)=><article data-reveal key={p.name}><span className="rv-step">0{<PriceText>{i+1}</PriceText>} / {<PriceText>{p.name}</PriceText>}</span><h3>{<PriceText>{p.title}</PriceText>}</h3><p>{<PriceText>{p.body}</PriceText>}</p><ul>{<PriceText>{p.items.map(item=><li key={item}>{<PriceText>{item}</PriceText>}</li>)}</PriceText>}</ul><Link href={p.href}> Découvrir {<PriceText>{p.name}</PriceText>} ↗</Link></article>)}</PriceText>}</div></div></section>
<section className="rv-section rv-connection" id="como-funciona" data-reveal><div className="shell"><p className="rv-label"> Comment tout se relie </p><h2> Une structure qui travaille <em>  ensemble. </em></h2><p className="rv-intro"> Le Profil d’entreprise aide votre client à vous trouver. Le site explique vos services et facilite le contact. Le SEO renforce cette structure dans les recherches. </p><div className="rv-flow"><span>Google</span><span>Site</span><span> Contact </span></div><p className="rv-flow-base"> Le SEO renforce chaque étape. </p></div></section>
<section className="rv-section rv-showcase" id="presenca-na-pratica"><div className="shell"><p className="rv-label" data-reveal> Votre présence numérique en pratique </p><h2 data-reveal> Découvrez ce que votre client <em>  trouvera. </em></h2><p className="rv-intro" data-reveal> Un profil qui présente votre entreprise. Un site qui explique vos services. Un moyen simple de vous contacter. </p><div className="rv-showcase-grid"><figure data-reveal><img src="/mockups/perfil-google.webp" alt="Démonstration fictive du Profil d’entreprise Google de Clínica Aurora sur un mobile" width="1122" height="1402" loading="lazy" decoding="async"/><figcaption><span className="rv-step">01 / Google</span><h3> Votre entreprise dans les recherches. </h3><p> Informations, services et photos réunis dans le Profil d’entreprise, lorsque l’entreprise est éligible. </p></figcaption></figure><figure data-reveal><img src="/mockups/site-mobile.webp" alt="Démonstration du site professionnel de Clínica Aurora adapté au mobile" width="1122" height="1402" loading="lazy" decoding="async"/><figcaption><span className="rv-step"> 02 / Site sur mobile </span><h3> De l’intérêt à la prise de contact. </h3><p> Des services clairs et un bouton de contact facile à trouver, même sur petit écran. </p></figcaption></figure><figure className="rv-showcase-desktop" data-reveal><img src="/mockups/site-desktop.webp" alt="Démonstration du site de Clínica Aurora sur un écran d’ordinateur" width="1536" height="1024" loading="lazy" decoding="async"/><figcaption><span className="rv-step"> 03 / Site sur ordinateur </span><h3> Une présentation à la hauteur de votre entreprise. </h3><p> La même identité, avec une expérience adaptée à chaque écran. </p></figcaption></figure></div><p className="rv-demo-note"> Exemples illustratifs avec l’entreprise fictive Clínica Aurora. Le projet est personnalisé pour votre entreprise. </p></div></section>
<section className="rv-section rv-included" data-reveal><div className="shell rv-split"><div><p className="rv-label"> Tout est inclus </p><h2> Services à distance au Brésil. <em> Une structure pour votre présence numérique. </em></h2><p> Une structure suivie de bout en bout, sans avoir à gérer vous-même l’hébergement, la maintenance et les optimisations. </p></div><ul className="rv-deliverables"><li> Profil d’entreprise Google, lorsque l’entreprise est éligible </li><li> Optimisations pour les recherches locales </li><li> Site professionnel et domaine </li><li> Hébergement, mises à jour et support </li><li> Structure SEO et optimisations continues </li></ul></div></section>
<section className="rv-section rv-offer" id="investimento" data-reveal><div className="shell rv-offer-grid rv-single-plan"><div><p className="rv-label"> Forfait de présence numérique </p><h2>Google + Site + SEO. <em> Votre présence numérique pendant un an. </em></h2></div><div className="rv-plan-visual-layout"><div className="rv-plan-list"><div className="rv-offer-price"><p> Forfait annuel unique </p><strong><PriceText>R$ 597,00 </PriceText><small> /an </small></strong><ExchangeNote/><span className="rv-plan-perk"> Sans frais d’installation </span><small> Payez par Pix, carte de crédit ou boleto. </small><ul className="rv-plan-services"><li> Mise en place de la présence numérique </li><li> Site professionnel d’une page </li><li> Domaine et hébergement gratuits </li><li> Maintenance </li><li> Améliorations SEO </li><li> Création et optimisation du Profil d’entreprise Google </li><li> Mises à jour et support </li></ul><span className="rv-plan-bonus"><strong> Bonus inclus </strong> Carte NFC pour les avis Google </span><small> Vous disposez de 7 jours pour vous rétracter. </small><DiagnosticCTA/></div></div><aside className="rv-nfc-preview" data-reveal><img src="/mockups/cartao-nfc.webp" alt="Modèle illustratif de carte NFC pour les avis Google à côté d’un mobile" width="1536" height="1024" loading="lazy" decoding="async"/><p className="rv-label"> Bonus du forfait annuel </p><h3> Facilitez l’invitation à laisser un avis. </h3><p> Votre client approche un mobile compatible de la carte NFC pour accéder au lien d’avis de votre entreprise sur Google. </p><p className="rv-demo-note"> Modèle illustratif de carte. L’avis est rédigé par le client lui-même. </p></aside></div></div></section>
<section className="rv-section rv-dark" data-reveal><div className="shell"><p className="rv-label"> Suivi continu </p><h2> Le site est mis en ligne. <em> Le travail continue. </em></h2><p className="rv-intro"> La mise en ligne est la première étape. Ensuite, nous suivons le Profil d’entreprise Google lorsque l’entreprise est éligible, maintenons le site fonctionnel et à jour, vérifions l’indexation et améliorons le SEO selon le périmètre convenu. Le forfait annuel comprend ce suivi pendant 12 mois. </p></div></section>
<section className="rv-section" data-reveal><div className="shell"><div className="rv-heading"><div><p className="rv-label"> Portfolio de sites </p><h2> Sites réalisés <em>  par Ravyt. </em></h2><p className="rv-portfolio-intro"> Démonstrations conceptuelles et sites publiés, présentés en mouvement. </p></div><Link href="/fr/cases"> Découvrir les projets ↗ </Link></div><Cases/></div></section>
<section className="rv-section rv-dark" id="sobre" data-reveal><div className="shell"><p className="rv-label"> Qui s’occupe de la structure </p><h2> Recherche et expérience. <br/><em> Dans la même direction. </em></h2><Team/><Link className="rv-text-link" href="/fr/sobre"> Découvrir Ravyt → </Link></div></section>
<section className="rv-section" data-reveal><div className="shell rv-split"><div><p className="rv-label"> Avant de décider </p><h2> De bonnes questions. <br/><em> Des réponses claires. </em></h2></div><FAQ/></div></section>
<section className="rv-final" data-reveal><div className="shell"><p className="rv-label"> Votre prochaine étape </p><h2> Vos prochains clients font déjà des recherches sur Google. </h2><p> Préparons votre entreprise pour qu’ils la trouvent. </p><DiagnosticCTA/></div></section>
</main><BlogFooter/></>}
