import test from 'node:test';
import assert from 'node:assert/strict';
import {PRICING,money,currencyForCountry,currencyForRequest,languageForRequest} from '../lib/i18n/regional.ts';
import {readFileSync} from 'node:fs';
const {default:worker}=await import('../dist/server/index.js');
const env={ASSETS:{fetch:async()=>new Response('',{status:404})}},ctx={waitUntil(){},passThroughOnException(){}};
const clean=html=>html.replace(/<script\b(?![^>]*application\/ld\+json)[^>]*>[\s\S]*?<\/script>/gi,'');
async function render(lang,country,currency,path=''){const req=new Request('https://ravytdigital.com'+(lang==='pt'?(path||'/'):'/'+lang+path),{headers:{cookie:`ravyt_language=${lang}`+(currency?`; ravyt_currency=${currency}`:'')}});Object.defineProperty(req,'cf',{value:{country}});const response=await worker.fetch(req,env,ctx);assert.equal(response.status,200);return clean(await response.text());}
test('annual price and mathematical equivalents have one source; geography uses only eurozone',()=>{assert.equal(PRICING.annual,597);assert.equal(PRICING.annual/PRICING.months,49.75);assert.equal(Number((PRICING.annual/PRICING.days).toFixed(2)),1.64);for(const [country,currency] of [['BR','BRL'],['US','USD'],['FR','EUR'],['BG','EUR'],['GB','USD'],['CH','USD'],['MX','USD']])assert.equal(currencyForCountry(country),currency);});
test('manual currency persists across every language and takes priority over country',()=>{for(const lang of ['pt','en','fr','es'])for(const currency of PRICING.currencies){assert.equal(currencyForRequest('BR',`ravyt_language=${lang}; ravyt_currency=${currency}`),currency);assert.equal(languageForRequest('/'+(lang==='pt'?'':lang),'ravyt_language='+lang,'fr','BR'),lang);}assert.equal(currencyForRequest('FR','ravyt_currency=GBP'),'EUR');});
test('all languages and manual currencies render 597 annual, 49.75 monthly, 1.64 daily and twelve months',async()=>{for(const lang of ['pt','en','fr','es'])for(const [country,defaultCurrency] of [['BR','BRL'],['US','USD'],['FR','EUR']])for(const manual of [undefined,...PRICING.currencies]){const currency=manual??defaultCurrency;const html=await render(lang,country,manual);const plan=html.match(/<div class="rv-offer-price"[\s\S]*?<\/ul>[\s\S]*?<\/a><\/div>/)?.[0];assert.ok(plan,lang+country);for(const value of [597,49.75,597/365])assert.ok(plan.includes(money(value,currency,lang)),`${lang} ${country} ${manual} ${value}`);assert.match(plan,/12/);assert.equal(/\bPix\b/.test(plan),country==='BR');assert.equal(/NFC/.test(plan),false);assert.equal(html.includes('src="/mockups/cartao-nfc.webp"'),country==='BR');assert.doesNotMatch(html,/\{\{(?:annual|monthly)\}\}/);}});
test('all commercial pages use localized equivalents and no international Pix or NFC bonus',async()=>{for(const lang of ['pt','en','fr','es'])for(const country of ['BR','US','FR'])for(const path of ['/sites-para-empresas-de-engenharia','/quanto-custa-criar-um-site','/criacao-de-sites-online','/blog/criacao-de-site-profissional-para-empresas']){const html=await render(lang,country,undefined,path);assert.ok(html.includes(money(597,currencyForCountry(country),lang)));assert.ok(html.includes(money(49.75,currencyForCountry(country),lang)));assert.doesNotMatch(html,/\{\{(?:annual|monthly)\}\}/);assert.equal(/\bPix\b/i.test(html),country==='BR');if(country!=='BR')assert.doesNotMatch(html,/NFC/);}});
test('pricing API has no rate fetch and follows remembered currency',async()=>{const original=globalThis.fetch;globalThis.fetch=()=>{throw new Error('FX fetch forbidden');};try{const req=new Request('https://ravytdigital.com/api/exchange-rates',{headers:{cookie:'ravyt_currency=EUR'}});Object.defineProperty(req,'cf',{value:{country:'BR'}});const data=await (await worker.fetch(req,env,ctx)).json();assert.equal(data.amount,597);assert.equal(data.currency,'EUR');assert.equal(data.rates,undefined);}finally{globalThis.fetch=original;}});
test('responsive styles preserve horizontal desktop and protect amounts on mobile',()=>{const css=readFileSync(new URL('../app/globals.css',import.meta.url),'utf8');assert.match(css,/rv-plan-visual-layout\{display:grid;grid-template-columns:minmax\(0,1fr\) minmax\(0,1fr\)/);assert.match(css,/@media\(max-width:800px\)/);assert.match(css,/rv-price-main>span[^}]*white-space:nowrap/);});
