import test from 'node:test';
import assert from 'node:assert/strict';
import {currencyForCountry,languageForRequest,parseRates,convertPrice} from '../lib/i18n/regional.ts';
const xml=`<Cube time='2026-10-02'><Cube currency='USD' rate='1.2'/><Cube currency='BRL' rate='5'/></Cube>`;
test('keeps 597 fixed in each regional currency independently of exchange rates',()=>{const rates=parseRates(xml);assert.equal(convertPrice('R$ 597,00 /year','EUR',rates,'en'),'€597.00 /year');assert.equal(convertPrice('R$ 597,00 /year','USD',rates,'en'),'$597.00 /year');assert.equal(convertPrice('R$ 597,00 /ano','BRL',rates,'pt'),'R$ 597,00 /ano');});
test('rejects missing, zero, invalid and future rates',()=>{for(const input of [xml.replace("rate='5'","rate='0'"),xml.replace("rate='1.2'","rate='NaN'"),xml.replace('2026-10-02','2099-12-31'),'<xml/>'])assert.throws(()=>parseRates(input));});
test('currency follows location independently of language',()=>{assert.equal(currencyForCountry('BR'),'BRL');assert.equal(currencyForCountry('FR'),'EUR');assert.equal(currencyForCountry('GB'),'EUR');assert.equal(currencyForCountry('US'),'USD');assert.equal(currencyForCountry('MX'),'USD');assert.equal(currencyForCountry(''),'USD');});
test('explicit URL and remembered language take priority; weighted browser languages and geography follow',()=>{assert.equal(languageForRequest('/fr/blog','ravyt_language=es','en-US','BR'),'fr');assert.equal(languageForRequest('/','a=b; ravyt_language=pt','fr','FR'),'pt');assert.equal(languageForRequest('/','','de;q=1,es;q=.8,en;q=.7','US'),'es');assert.equal(languageForRequest('/','','en;q=0,fr;q=.6','BR'),'fr');assert.equal(languageForRequest('/','','','MX'),'es');assert.equal(languageForRequest('/','','',''),'pt');});
const {default:worker}=await import('../dist/server/index.js');
const env={ASSETS:{fetch:async()=>new Response('',{status:404})}},ctx={waitUntil(){},passThroughOnException(){}};
const request=(path,headers={})=>worker.fetch(new Request('https://ravytdigital.com'+path,{headers}),env,ctx);
test('Pix is offered only in Brazil in all four languages and commercial pages',async()=>{
 for(const country of ['BR','FR','US'])for(const lang of ['pt','en','fr','es'])for(const path of ['', '/sites-para-empresas-de-engenharia', '/quanto-custa-criar-um-site','/blog/criacao-de-site-profissional-para-empresas']){
  const req=new Request('https://ravytdigital.com'+(lang==='pt'?(path||'/'):'/'+lang+path),{headers:{cookie:`ravyt_language=${lang}`}});
  Object.defineProperty(req,'cf',{value:{country}});
  const response=await worker.fetch(req,env,ctx);assert.equal(response.status,200);
  const html=await response.text();
  const rendered=html.replace(/<script\b(?![^>]*application\/ld\+json)[^>]*>[\s\S]*?<\/script>/gi,'');
  assert.equal(/\bPix\b/i.test(rendered),country==='BR',`${country} ${lang} ${path}`);
 }
});
test('production redirects preserve paths, query strings and manual preference',async()=>{let response=await request('/sites?utm_source=test',{'accept-language':'es-ES'});assert.equal(response.status,307);assert.equal(response.headers.get('location'),'https://ravytdigital.com/es/sites?utm_source=test');response=await request('/',{'accept-language':'fr',cookie:'ravyt_language=pt'});assert.equal(response.status,200);assert.equal((await request('/robots.txt',{'accept-language':'fr'})).status,200);});
test('three complete localized homepages and representative pages render with correct language, annual period, services and navigation',async()=>{for(const [lang,period,title] of [['en','/year','Single annual plan'],['fr','/an','Forfait annuel unique'],['es','/año','Plan único anual']]){for(const path of ['', '/sites','/contato','/politica-de-cookies','/blog/site-institucional-paginas-essenciais']){const response=await request('/'+lang+path);assert.equal(response.status,200,lang+path);const html=await response.text();assert.match(html,new RegExp('<html[^>]*lang="'+lang+'"'));assert.equal((html.match(/<h1[ >]/g)??[]).length,1,lang+path);if(path!=='/politica-de-cookies')assert.ok(html.includes('/'+lang+'/sites'));if(!path){assert.ok(html.includes(period));assert.ok(html.includes(title),lang+' annual title');assert.ok(!html.includes('<small>/ano</small>'));assert.ok(html.includes('597'));assert.ok(!html.includes('Conversão pela cotação')); assert.match(html,/hreflang="fr"/i);}}}});
test('the exchange endpoint returns validated rates with location-specific currency and no shared personalized cache',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response(xml);try{for(const [country,currency] of [['BR','BRL'],['FR','EUR'],['US','USD']]){const req=new Request('https://ravytdigital.com/api/exchange-rates');Object.defineProperty(req,'cf',{value:{country}});const response=await worker.fetch(req,env,ctx);assert.equal(response.status,200);assert.match(response.headers.get('cache-control'),/no-store/);const data=await response.json();assert.equal(data.currency,currency);assert.equal(data.amount,597);assert.equal(data.period,'year');assert.equal(data.pricing,'fixed-regional');assert.equal(data.rates,undefined);}}finally{globalThis.fetch=original;}});
