import { pageMetadata } from "@/lib/metadata";
import type { Metadata } from "next";
import Image from "next/image";
import { BlogFooter, BlogHeader } from "@/components/BlogChrome";
import { whatsappUrl } from "@/lib/contact";
import { SITE_URL } from "@/lib/site";
import { ytala } from "@/lib/structured-data";
import StructuredData from "@/components/StructuredData";
import Link from "next/link";
import { posts } from "@/app/blog/posts";
export const metadata: Metadata = pageMetadata({ title:"Ytala Cabral | Social Media para Psicólogos Parentais", description:"Conheça Ytala Cabral, especialista à frente da Ravyt Digital e Social Media da psicóloga parental Nanda Perim, da PSIMAMA.", alternates:{canonical:"/autores/ytala-cabral"} });
export default function Page(){ const schema={"@context":"https://schema.org","@type":"ProfilePage","@id":`${SITE_URL}/autores/ytala-cabral#profile`,url:`${SITE_URL}/autores/ytala-cabral`,name:"Ytala Cabral — Ravyt Digital",mainEntity:ytala}; return <><BlogHeader/><main id="conteudo" tabIndex={-1} className="specialist-page"><StructuredData data={schema}/><section className="about-specialist"><div className="shell two-columns"><div className="team-photo-ytala"><Image src="/team/ytala-cabral.webp" alt="Ytala Cabral" width={720} height={900} unoptimized/></div><div><p className="section-kicker">Especialista da Ravyt Digital</p><h1>Ytala Cabral</h1><p>Ytala Cabral é Social Media especializada em Psicologia Parental à frente da Ravyt Digital.</p><p>Atua como Social Media da psicóloga parental Nanda Perim, fundadora da PSIMAMA. Essa experiência sustenta um trabalho de conteúdo atento à linguagem, à ética e às particularidades da comunicação com famílias.</p><p>Na Ravyt, desenvolve posicionamento, planejamento editorial, copy e direção de conteúdo para psicólogos parentais de todo o Brasil.</p><a className="button button-dark" href={whatsappUrl()} target="_blank" rel="noopener noreferrer">CONVERSAR COM YTALA</a></div></div></section><section className="insights-section"><div className="shell"><p className="section-kicker">Conteúdo de Ytala Cabral</p><h2>Artigos sobre comunicação para Psicologia Parental</h2><div className="insights-grid">{posts.filter(post=>!post.author).map(post=><Link key={post.slug} href={`/blog/${post.slug}`}><strong>{post.title}</strong><span>{post.excerpt}</span></Link>)}</div></div></section></main><BlogFooter/></>; }
