import Breadcrumbs from "@/components/Breadcrumbs";
import type { Metadata } from "next";
import Link from "next/link";
import { pageMetadata } from "@/lib/metadata";
import { BlogFooter, BlogHeader } from "@/components/BlogChrome";
import { whatsappUrl } from "@/lib/contact";
import { SITE_URL } from "@/lib/site";

export const metadata: Metadata = pageMetadata({
  title:"Preço da Gestão de Mídias Sociais: O que Está Incluído",
  description:"Entenda o que muda no preço da gestão de mídias sociais: estratégia, produção, publicação e análise. Compare escopos e peça uma proposta à Ravyt.",
  alternates:{canonical:"/quanto-custa-gestao-de-midias-sociais"},
});

export default function Page(){
  const schema={"@context":"https://schema.org","@type":"WebPage",name:"Quanto custa a gestão de mídias sociais?",url:`${SITE_URL}/quanto-custa-gestao-de-midias-sociais`,about:{"@id":`${SITE_URL}/gestao-de-midias-sociais#service`},publisher:{"@id":`${SITE_URL}/#organization`}};
  return <><BlogHeader current="social"/><main id="conteudo" tabIndex={-1} className="specialist-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
    <header className="specialist-hero"><div className="shell"><Breadcrumbs items={[{name:"Início",href:"/"},{name:"Gestão de Mídias Sociais",href:"/gestao-de-midias-sociais"},{name:"Orçamento de gestão de mídias sociais",href:"/quanto-custa-gestao-de-midias-sociais"}]} /><p className="section-kicker">Preço da gestão de mídias sociais</p><h1>Quanto custa contratar a gestão de redes sociais?</h1><p>Antes de comparar mensalidades, compare o trabalho contratado. Planejar, criar posts e assumir publicação e análise são escopos diferentes. A proposta precisa deixar claro quem faz cada parte.</p><a className="button button-light" href={whatsappUrl("Olá! Quero pedir uma proposta de gestão de mídias sociais. Meu negócio é:")} target="_blank" rel="noopener noreferrer">PEDIR UMA PROPOSTA</a></div></header>
    <section className="specialist-section"><div className="shell two-columns"><div><p className="section-kicker">O que compõe o preço</p><h2>Quantidade de posts é apenas uma parte do orçamento.</h2><p>O valor muda com a profundidade do diagnóstico, os canais atendidos, os formatos produzidos, o volume de vídeos e a responsabilidade por publicar e acompanhar o desempenho.</p><p>Na <Link href="/gestao-de-midias-sociais">gestão completa de mídias sociais</Link>, a Ravyt trabalha da estratégia à análise. Também é possível conversar sobre produção sem gestão ou consultoria estratégica, conforme a necessidade do negócio.</p></div><div className="check-list"><p><strong>Estratégia:</strong> diagnóstico, posicionamento, linhas editoriais e calendário.</p><p><strong>Produção:</strong> pautas, textos, carrosséis, roteiros e edição de vídeos conforme o escopo.</p><p><strong>Operação:</strong> organização e publicação do conteúdo, quando contratadas.</p><p><strong>Acompanhamento:</strong> análise de resultados e ajustes para os próximos ciclos, quando contratados.</p></div></div></section>
    <section className="process-section"><div className="shell"><p className="section-kicker">Compare propostas</p><h2>Quatro perguntas antes de escolher.</h2><div className="process-grid"><article><span>01</span><h3>Quem planeja?</h3><p>Há diagnóstico e direção editorial ou apenas execução de pautas enviadas pelo cliente?</p></article><article><span>02</span><h3>O que será produzido?</h3><p>Quais formatos, quantos conteúdos e quantas revisões estão previstos?</p></article><article><span>03</span><h3>Quem publica?</h3><p>A agência assume calendário e publicação ou entrega os arquivos para sua equipe?</p></article><article><span>04</span><h3>Quem analisa?</h3><p>Existe acompanhamento de desempenho e ajuste de estratégia ou a entrega termina nos posts?</p></article></div></div></section>
    <section className="faq-section"><div className="shell"><p className="section-kicker">Dúvidas frequentes</p><h2>Antes de fechar o contrato</h2><div className="faq-list"><details><summary>Existe um preço único por post?</summary><p>Uma peça isolada não representa o trabalho de estratégia, planejamento, publicação e acompanhamento. Peça que cada proposta detalhe suas entregas.</p></details><details><summary>Posso contratar só a produção?</summary><p>Sim. Nesse formato, a Ravyt produz conteúdo conforme o escopo combinado, enquanto publicação e acompanhamento ficam fora da contratação.</p></details><details><summary>A gestão garante novos clientes?</summary><p>Não há garantia de quantidade de clientes. A gestão organiza a comunicação e permite acompanhar o que funciona para ajustar as decisões.</p></details></div></div></section>
    <section className="final-specialist-cta"><div className="shell"><h2>Qual escopo faz sentido para sua empresa?</h2><p>Conte como sua comunicação funciona hoje e quais tarefas você quer assumir ou delegar. Atendimento em todo o Brasil.</p><a className="button button-light" href={whatsappUrl("Olá! Quero pedir uma proposta de gestão de mídias sociais. Meu negócio é:")} target="_blank" rel="noopener noreferrer">CONVERSAR SOBRE O ORÇAMENTO</a></div></section>
  </main><BlogFooter/></>;
}
