export type BlogPost = { slug:string; title:string; excerpt:string; category:string; date:string; dateLabel:string; readingTime:string; intro:string; sections:{title:string; paragraphs:string[]}[] };

export const posts: BlogPost[] = [
  {slug:"conteudo-para-psicologos-parentais",title:"Conteúdo para Psicólogos Parentais: o que precisa vir antes do calendário",excerpt:"Antes de definir formatos e frequência, a comunicação precisa traduzir com clareza o trabalho do psicólogo parental.",category:"Estratégia de conteúdo",date:"2026-09-02",dateLabel:"2 de setembro de 2026",readingTime:"6 min de leitura",intro:"Um calendário cheio não garante uma presença digital forte. Para o psicólogo parental, a estratégia começa quando cada conteúdo ajuda famílias a compreenderem o problema, o cuidado possível e os limites da atuação profissional.",sections:[{title:"O posicionamento organiza todas as decisões",paragraphs:["Antes das pautas, é preciso definir o que o profissional deseja tornar reconhecível: sua abordagem, os temas que domina, o público com quem trabalha e a forma como orienta famílias.","Essa base evita um perfil que fala de muitos assuntos, mas não constrói uma percepção clara sobre a especialidade."]},{title:"A pauta deve nascer de dúvidas reais",paragraphs:["Perguntas recebidas em atendimentos, aulas e conversas com famílias revelam dúvidas mais úteis do que listas genéricas de ideias. Elas ajudam a produzir conteúdo específico, responsável e conectado à realidade do público.","A comunicação pode educar sem transformar um post em consulta, diagnóstico ou promessa de resultado."]},{title:"Constância é consequência de um processo",paragraphs:["Quando posicionamento, pilares e formatos estão definidos, o calendário deixa de depender de inspiração. A produção passa a seguir um processo com pauta, escrita, revisão e direção visual."]}]},
  {slug:"comunicacao-etica-psicologia-parental",title:"Comunicação ética na Psicologia Parental: acolher sem explorar vulnerabilidades",excerpt:"Como comunicar dores familiares com responsabilidade, clareza e respeito aos limites do conteúdo digital.",category:"Comunicação responsável",date:"2026-09-02",dateLabel:"2 de setembro de 2026",readingTime:"5 min de leitura",intro:"Temas como culpa, limites, vínculo e desenvolvimento infantil exigem cuidado. Uma comunicação forte não precisa aumentar o medo dos pais para chamar atenção; ela precisa ajudar o público a compreender situações complexas com mais clareza.",sections:[{title:"Dor não deve virar atalho para alcance",paragraphs:["Ganchos alarmistas podem gerar cliques, mas também simplificam experiências familiares delicadas. O conteúdo precisa contextualizar, evitar julgamentos e não tratar comportamentos isolados como diagnóstico."]},{title:"Orientar não é substituir atendimento",paragraphs:["Posts podem apresentar conceitos, perguntas e caminhos de reflexão. Ainda assim, precisam deixar claros os limites entre educação, orientação parental e acompanhamento psicológico individualizado."]},{title:"Confiança se constrói na linguagem",paragraphs:["Uma linguagem acessível não precisa ser infantilizada. Explicar termos, reconhecer nuances e evitar promessas absolutas fortalece a autoridade sem transformar o profissional em personagem de internet."]}]},
  {slug:"autoridade-digital-psicologo-parental",title:"Autoridade digital para Psicólogos Parentais não é falar difícil",excerpt:"Autoridade nasce da clareza, da coerência e da capacidade de transformar conhecimento em orientação útil.",category:"Posicionamento",date:"2026-09-02",dateLabel:"2 de setembro de 2026",readingTime:"5 min de leitura",intro:"Muitos profissionais tentam demonstrar conhecimento usando uma linguagem excessivamente técnica. Nas redes sociais, isso pode afastar exatamente as famílias que precisam compreender o tema.",sections:[{title:"Clareza demonstra domínio",paragraphs:["Quem conhece profundamente um assunto consegue organizar o raciocínio, escolher exemplos responsáveis e explicar sem perder precisão. Clareza não reduz a autoridade; ela torna o conhecimento utilizável."]},{title:"Coerência torna o profissional reconhecível",paragraphs:["Quando os conteúdos repetem princípios, pontos de vista e áreas de atuação de forma consistente, o público passa a associar o profissional a uma perspectiva própria."]},{title:"Prova não é apenas depoimento",paragraphs:["Experiência, processos, referências, bastidores de estudo e critérios de trabalho também ajudam a demonstrar seriedade. A prova mais importante é a coerência entre o que o profissional defende e como se comunica."]}]},
];

export function getPost(slug:string){ return posts.find((post)=>post.slug===slug); }
