
import {PriceText} from "@/components/i18n/Regional";
import Image from 'next/image';
import Link from 'next/link';
import { projects, questions } from "@/locales/en/lib/commercial";
import PortfolioPreview from "@/locales/en/components/PortfolioPreview";
export function DiagnosticCTA(){return <Link className="rv-button" href="/en/diagnostico" data-track="primary_cta_click"> I want to strengthen my Google presence <span aria-hidden="true">↗</span></Link>;}
export function FinalCTA(){return <section className="rv-final"><div className="shell"><p className="rv-label"> Your next step </p><h2> Your customer is already searching. <br/> What do they find about you? </h2><p> Let’s look at your business and understand what needs attention first. </p><DiagnosticCTA/></div></section>;}
export function Cases(){return <div className="rv-cases">{<PriceText>{projects.map(p=><article key={p.slug}><PortfolioPreview slug={p.slug} name={p.name}/><p className="rv-label">{<PriceText>{p.type}</PriceText>}</p><h3>{<PriceText>{p.name}</PriceText>}</h3><p>{<PriceText>{p.text}</PriceText>}{<PriceText>{'nicheHref' in p && p.nicheHref && <><br/><Link href={p.nicheHref}>{<PriceText>{p.nicheLabel}</PriceText>} →</Link></>}</PriceText>}</p></article>)}</PriceText>}</div>;}
export function Team(){return <div className="rv-team"><article><Image src="/team/ytala-cabral-card.webp" alt="Ytala Cabral" width={320} height={464} unoptimized/><div><p className="rv-label"> Be found and understood </p><h3>Ytala Cabral</h3><strong> SEO · Google Business Profile · Copywriting </strong><p> Research, search intent and messaging. Ytala connects what your customer looks for with what your business needs to communicate. </p></div></article><article><Image src="/team/marcio-cabral-card.webp" alt="Marcio Cabral" width={280} height={380} unoptimized/><div><p className="rv-label"> Be chosen and contacted </p><h3>Marcio Cabral</h3><strong>UX/UI · Web Design</strong><p> Architecture, design and implementation. Marcio turns strategy into a clear, accessible experience ready for the next click. </p></div></article></div>;}
export function FAQ(){return <div className="rv-faq">{<PriceText>{questions.map(([q,a])=><details key={q}><summary>{<PriceText>{q}</PriceText>}</summary><p>{<PriceText>{a}</PriceText>}</p></details>)}</PriceText>}</div>;}
