
import {PriceText} from "@/components/i18n/Regional";
import Link from 'next/link';
import { BlogHeader, BlogFooter } from "@/locales/en/components/BlogChrome";
import { DiagnosticCTA, FinalCTA } from "@/locales/en/components/Commercial";
import StructuredData from "@/locales/en/components/StructuredData";
import { services } from "@/locales/en/lib/commercial";
import { SITE_URL } from '@/lib/site';
export default function ServicePage({slug}:{slug:string}){const s=services.find(s=>s.slug===slug)!;return <><BlogHeader/><main id="conteudo" tabIndex={-1} className="rv"><StructuredData data={{'@context':'https://schema.org','@type':'Service',name:s.name,description:s.description,url:SITE_URL+"/en/"+slug,provider:{'@id':SITE_URL+'/#organization'},areaServed:"Brazil"}}/><section className="rv-page-hero"><div className="shell"><p className="rv-label">Ravyt Digital / {<PriceText>{s.name}</PriceText>}</p><h1>{<PriceText>{s.title}</PriceText>}</h1><p className="rv-lead">{<PriceText>{s.description}</PriceText>}</p><DiagnosticCTA/></div></section><section className="rv-section"><div className="shell rv-split"><div><h2> Before the tool, <br/><em>  your business. </em></h2><p>{<PriceText>{s.detail}</PriceText>}</p></div><div><h2 className="rv-small-heading"> What may be included </h2><ul className="rv-deliverables">{<PriceText>{s.items.map(i=><li key={i}>{<PriceText>{i}</PriceText>}</li>)}</PriceText>}</ul><p> The scope is defined after understanding your starting point. You receive a proposal with priorities, deliverables and responsibilities. </p></div></div></section><section className="rv-section rv-dark"><div className="shell"><p className="rv-label"> How we start </p><h2> Understand. Prioritize. Implement. Monitor. </h2><p className="rv-intro"> We analyze current channels and business goals, decide what to address first and agree on how to monitor progress. We do not promise Google rankings or a guaranteed number of contacts. </p><div className="rv-actions">{<PriceText>{services.filter(x=>x.slug!==slug).map(x=><Link href={"/en/"+x.slug} key={x.slug}> Explore {<PriceText>{x.name}</PriceText>} →</Link>)}</PriceText>}</div></div></section><FinalCTA/></main><BlogFooter/></>;}
