import {ExchangeNote} from "@/components/i18n/Regional";

import {PriceText} from "@/components/i18n/Regional";
import Link from 'next/link';
import { BlogHeader, BlogFooter } from "@/locales/es/components/BlogChrome";
import { Cases, DiagnosticCTA, FAQ, Team } from "@/locales/es/components/Commercial";
import ScrollReveal from "@/locales/es/components/ScrollReveal";
import { pageMetadata } from "@/locales/es/lib/metadata";
export const metadata = pageMetadata({title:"Google + Sitio web + SEO para empresas",description:"Presencia digital con sitio profesional, mantenimiento y SEO. Plan único anual de R$ 597,00, pagado por Pix, tarjeta o boleto, con los mismos servicios de Google, sitio web y SEO.",alternates:{canonical:"/es"}});
const pillars=[
  {name:'Google',title:"Perfil de Empresa en Google y presencia local.",body:"Organizamos y optimizamos el Perfil de Empresa en Google, cuando el negocio es elegible, con información coherente para búsquedas locales.",items:["Configuración e información del negocio","Optimizaciones para búsquedas locales","Mejoras continuas"],href:"/es/google-meu-negocio"},
  {name:"Sitio web",title:"Creación de sitios web profesionales.",body:"Creamos y mantenemos un sitio profesional que presenta tu empresa, transmite confianza y facilita el contacto.",items:["Creación del sitio y dominio","Alojamiento y actualizaciones","Soporte continuo"],href:"/es/sites"},
  {name:'SEO',title:"SEO local y estructura para búsquedas.",body:"Trabajamos la estructura y las páginas del sitio para que los buscadores comprendan mejor tu negocio.",items:["Estructura técnica de SEO","Optimización de las páginas","Seguimiento y mejoras"],href:"/es/seo"}
];
export default function Home(){return <><BlogHeader transparent/><main id="conteudo" tabIndex={-1} className="rv"><ScrollReveal/>
<section className="rv-hero"><video className="rv-hero-video" autoPlay muted loop playsInline preload="metadata" poster="/hero/ravyt-poster-20260927.webp" aria-hidden="true"><source src="/hero-video-20260927" type="video/mp4" /></video><div className="rv-hero-shade" aria-hidden="true"/><div className="shell rv-hero-inner"><p className="rv-label"> Google • Sitio web • SEO </p><h1> Google + Sitio web + SEO para empresas <em>  en todo Brasil. </em></h1><p className="rv-lead"> Tu negocio necesita ser encontrado cuando los clientes buscan. Creamos tu sitio y trabajamos tu presencia en Google para transformar búsquedas en oportunidades. </p><div className="rv-actions"><DiagnosticCTA/><a href="#como-funciona"> Entender cómo funciona ↓ </a></div><p className="rv-hero-note"><PriceText> Plan único anual: R$ 597,00 · Pix, tarjeta o boleto </PriceText></p></div><div className="shell rv-hero-bottom"><span> Ser encontrada es el comienzo. </span><span> Ser elegida es el siguiente paso. </span></div></section>
<section className="rv-section rv-problem" data-reveal><div className="shell"><p className="rv-label"> La demanda ya existe </p><h2> Cuando alguien busca lo que ofreces, ¿encuentra tu empresa <em>  o a tu competidor? </em></h2><p className="rv-intro"> Estar en Internet no significa ser encontrado. Tu empresa necesita aparecer en las búsquedas, transmitir confianza y ofrecer un camino sencillo para que el cliente contacte contigo. </p><ol className="rv-path"><li> Investigación </li><li> Encuentra </li><li> Confía </li><li> Contacta </li></ol></div></section>
<section className="rv-section rv-dark" data-reveal><div className="shell"><p className="rv-label"> La solución Ravyt </p><h2> Una estructura completa para que tu empresa <em>  crezca en Google. </em></h2><p className="rv-intro"> Unimos presencia local, sitio profesional y SEO en una sola estrategia para construir y mantener una presencia digital más fuerte para tu negocio. </p></div></section>
<section className="rv-section rv-services" id="servicos"><div className="shell"><p className="rv-label" data-reveal> Tres pilares. Una oferta. </p><h2 data-reveal> Google + Sitio web + SEO. </h2><div className="rv-pillars">{<PriceText>{pillars.map((p,i)=><article data-reveal key={p.name}><span className="rv-step">0{<PriceText>{i+1}</PriceText>} / {<PriceText>{p.name}</PriceText>}</span><h3>{<PriceText>{p.title}</PriceText>}</h3><p>{<PriceText>{p.body}</PriceText>}</p><ul>{<PriceText>{p.items.map(item=><li key={item}>{<PriceText>{item}</PriceText>}</li>)}</PriceText>}</ul><Link href={p.href}> Conocer {<PriceText>{p.name}</PriceText>} ↗</Link></article>)}</PriceText>}</div></div></section>
<section className="rv-section rv-connection" id="como-funciona" data-reveal><div className="shell"><p className="rv-label"> Cómo se conecta todo </p><h2> Una estructura trabajando <em>  en conjunto. </em></h2><p className="rv-intro"> El Perfil de Empresa ayuda a tu cliente a encontrarte. El sitio explica tus servicios y facilita el contacto. El SEO fortalece esta estructura en las búsquedas. </p><div className="rv-flow"><span>Google</span><span> Sitio web </span><span> Contacto </span></div><p className="rv-flow-base"> El SEO fortalece cada etapa. </p></div></section>
<section className="rv-section rv-showcase" id="presenca-na-pratica"><div className="shell"><p className="rv-label" data-reveal> Tu presencia digital en la práctica </p><h2 data-reveal> Mira lo que tu cliente <em>  va a encontrar. </em></h2><p className="rv-intro" data-reveal> Un perfil que presenta tu negocio. Un sitio que explica tus servicios. Un camino sencillo para contactar. </p><div className="rv-showcase-grid"><figure data-reveal><img src="/mockups/perfil-google.webp" alt="Demostración ficticia del Perfil de Empresa en Google de Clínica Aurora en un móvil" width="1122" height="1402" loading="lazy" decoding="async"/><figcaption><span className="rv-step">01 / Google</span><h3> Tu negocio en las búsquedas. </h3><p> Información, servicios y fotos reunidos en el Perfil de Empresa, cuando el negocio es elegible. </p></figcaption></figure><figure data-reveal><img src="/mockups/site-mobile.webp" alt="Demostración del sitio profesional de Clínica Aurora adaptado al móvil" width="1122" height="1402" loading="lazy" decoding="async"/><figcaption><span className="rv-step"> 02 / Sitio web en el móvil </span><h3> Del interés al contacto. </h3><p> Servicios claros y un botón de contacto fácil de encontrar, también en la pantalla pequeña. </p></figcaption></figure><figure className="rv-showcase-desktop" data-reveal><img src="/mockups/site-desktop.webp" alt="Demostración del sitio de Clínica Aurora en un monitor de ordenador" width="1536" height="1024" loading="lazy" decoding="async"/><figcaption><span className="rv-step"> 03 / Sitio web en el ordenador </span><h3> Una presentación a la altura de tu negocio. </h3><p> La misma identidad, con una experiencia adaptada a cada pantalla. </p></figcaption></figure></div><p className="rv-demo-note"> Ejemplos ilustrativos con la empresa ficticia Clínica Aurora. El proyecto se personaliza para tu negocio. </p></div></section>
<section className="rv-section rv-included" data-reveal><div className="shell rv-split"><div><p className="rv-label"> Todo incluido </p><h2> Atención remota en Brasil. <em> Una estructura para tu presencia digital. </em></h2><p> Una estructura acompañada de principio a fin, sin tener que administrar alojamiento, mantenimiento y optimizaciones por tu cuenta. </p></div><ul className="rv-deliverables"><li> Perfil de Empresa en Google, cuando el negocio es elegible </li><li> Optimizaciones para búsquedas locales </li><li> Sitio profesional y dominio </li><li> Alojamiento, actualizaciones y soporte </li><li> Estructura de SEO y optimizaciones continuas </li></ul></div></section>
<section className="rv-section rv-offer" id="investimento" data-reveal><div className="shell rv-offer-grid rv-single-plan"><div><p className="rv-label"> Plan de presencia digital </p><h2> Google + Sitio web + SEO. <em> Tu presencia digital durante un año. </em></h2></div><div className="rv-plan-visual-layout"><div className="rv-plan-list"><div className="rv-offer-price"><p> Plan único anual </p><strong><PriceText>R$ 597,00 </PriceText><small> /año </small></strong><ExchangeNote/><span className="rv-plan-perk"> Sin tarifa de implementación </span><small> Paga por Pix, tarjeta de crédito o boleto. </small><ul className="rv-plan-services"><li> Implementación de la presencia digital </li><li> Sitio profesional de una página </li><li> Dominio y alojamiento gratis </li><li> Mantenimiento </li><li> Mejoras de SEO </li><li> Creación y optimización del Perfil de Empresa en Google </li><li> Actualizaciones y soporte </li></ul><span className="rv-plan-bonus"><strong> Bono incluido </strong> Tarjeta NFC de reseñas de Google </span><small> Tienes 7 días para desistir de la contratación. </small><DiagnosticCTA/></div></div><aside className="rv-nfc-preview" data-reveal><img src="/mockups/cartao-nfc.webp" alt="Modelo ilustrativo de tarjeta NFC para reseñas de Google junto a un móvil" width="1536" height="1024" loading="lazy" decoding="async"/><p className="rv-label"> Bono del plan anual </p><h3> Facilita la invitación a dejar una reseña. </h3><p> Tu cliente acerca un móvil compatible a la tarjeta NFC para acceder al enlace de reseñas de tu empresa en Google. </p><p className="rv-demo-note"> Modelo ilustrativo de tarjeta. La reseña la hace el propio cliente. </p></aside></div></div></section>
<section className="rv-section rv-dark" data-reveal><div className="shell"><p className="rv-label"> Seguimiento continuo </p><h2> El sitio se publica. <em> El trabajo continúa. </em></h2><p className="rv-intro"> Publicar el sitio es la primera etapa. Después, acompañamos el Perfil de Empresa en Google cuando el negocio es elegible, mantenemos el sitio funcionando y actualizado, revisamos la indexación y mejoramos el SEO según el alcance contratado. El plan anual incluye este cuidado durante 12 meses. </p></div></section>
<section className="rv-section" data-reveal><div className="shell"><div className="rv-heading"><div><p className="rv-label"> Portafolio de sitios web </p><h2> Sitios creados <em>  por Ravyt. </em></h2><p className="rv-portfolio-intro"> Demostraciones conceptuales y sitios publicados, presentados en movimiento. </p></div><Link href="/es/cases"> Conocer los proyectos ↗ </Link></div><Cases/></div></section>
<section className="rv-section rv-dark" id="sobre" data-reveal><div className="shell"><p className="rv-label"> Quién cuida la estructura </p><h2> Búsqueda y experiencia. <br/><em> En la misma dirección. </em></h2><Team/><Link className="rv-text-link" href="/es/sobre"> Conocer Ravyt → </Link></div></section>
<section className="rv-section" data-reveal><div className="shell rv-split"><div><p className="rv-label">Antes de decidir</p><h2> Buenas preguntas. <br/><em> Respuestas claras. </em></h2></div><FAQ/></div></section>
<section className="rv-final" data-reveal><div className="shell"><p className="rv-label"> Tu siguiente paso </p><h2> Tus próximos clientes ya están buscando en Google. </h2><p> Vamos a preparar tu empresa para que la encuentren. </p><DiagnosticCTA/></div></section>
</main><BlogFooter/></>}
