import Image from "next/image";
import Link from "next/link";
import { BlogFooter, BlogHeader } from "@/components/BlogChrome";
import { whatsappUrl } from "@/lib/contact";

const services = [
  { number:"01", title:"Gestão de mídias sociais", text:"Estratégia, calendário, criação de conteúdo, publicação e análise para sua marca se comunicar com clareza e consistência.", href:"/gestao-de-midias-sociais" },
  { number:"02", title:"Criação de sites online", text:"Sites com domínio próprio, páginas claras e uma estrutura preparada para apresentar seu trabalho e facilitar o contato.", href:"/criacao-de-sites-online" },
];

export default function Home() {
  return <>
    <BlogHeader />
    <main id="conteudo" tabIndex={-1}>
      <section className="specialist-home-hero"><div className="shell hero-specialist-grid"><div className="hero-specialist-copy"><p className="eyebrow">Ravyt Digital · Atendimento em todo o Brasil</p><h1>Gestão de mídias sociais e criação de sites para sua marca ser encontrada.</h1><p className="hero-lead">Organizamos sua comunicação nas redes e construímos seu espaço próprio na internet. Duas frentes para apresentar seu trabalho com clareza e abrir caminhos para novos contatos.</p><div className="hero-actions"><a className="button button-light" href={whatsappUrl()} target="_blank" rel="noopener noreferrer">CONVERSAR COM A RAVYT</a><a className="button button-ghost" href="#servicos">Conhecer os serviços</a></div></div></div></section>
      <section className="home-services" id="servicos"><div className="shell"><p className="section-kicker">O que fazemos</p><h2>Escolha por onde sua presença digital precisa começar.</h2><div className="service-duo">{services.map(service=><article key={service.number}><span>{service.number}</span><h3>{service.title}</h3><p>{service.text}</p><Link href={service.href}>Conhecer o serviço →</Link></article>)}</div></div></section>
      <section className="difference-section"><div className="shell two-columns"><div><p className="section-kicker">Presença digital com direção</p><h2>Seu público pode chegar por mais de um caminho.</h2><p>Há quem descubra um profissional pelo conteúdo. Há quem pesquise o serviço no Google ou receba uma indicação e queira conhecer melhor o negócio antes de entrar em contato.</p></div><div className="check-list"><p><strong>Nas redes:</strong> uma comunicação planejada ajuda as pessoas a entender seu trabalho e acompanhar sua marca.</p><p><strong>No seu site:</strong> serviços, diferenciais e formas de contato ficam reunidos em um endereço com domínio próprio.</p><p><strong>Na estratégia:</strong> cada canal cumpre uma função e direciona o próximo passo de quem chega até você.</p></div></div></section>
      <section className="about-specialist" id="sobre"><div className="shell two-columns"><div className="team-photo-ytala"><Image src="/team/ytala-cabral.webp" alt="Ytala Cabral, à frente da Ravyt Digital" width={720} height={900} unoptimized /></div><div><p className="section-kicker">A Ravyt Digital</p><h2>Comunicação clara, do conteúdo ao site.</h2><p>Ytala Cabral conduz a estratégia de comunicação da Ravyt. A agência trabalha com gestão de mídias sociais e criação de sites online para profissionais e empresas que precisam apresentar seus serviços com clareza.</p><p>O atendimento é remoto e está disponível em todo o Brasil. Cada projeto começa pela compreensão do negócio, do público e do objetivo que a presença digital precisa atender.</p><Link href="/contato">Converse sobre seu projeto →</Link></div></div></section>
      <section className="client-testimonial" aria-labelledby="testimonial-title"><div className="shell testimonial-layout"><div className="testimonial-heading"><p className="section-kicker">Depoimento sobre gestão de conteúdo</p><h2 id="testimonial-title">Quem trabalhou com a Ravyt conta como foi.</h2><div className="testimonial-person"><span className="testimonial-monogram" aria-hidden="true">RZ</span><div><strong>Rafaela Zanandrea</strong><span>Psicóloga intercultural</span><span>Norte da Virgínia, Estados Unidos</span><a href="https://www.instagram.com/rafaelazanapsi/" target="_blank" rel="noopener noreferrer" aria-label="Ver o perfil de Rafaela Zanandrea no Instagram">@rafaelazanapsi ↗</a></div></div></div><blockquote><p>“Adorei trabalhar com a Ytala! Ela é uma profissional muito competente, inteligente, objetiva, criativa e muito paciente (eu não entendia nada do universo de MKT e Ytala sempre, com muita paciência e cuidado, me explicava 🥰).</p><p>Desde o início, ela entendeu muito rápido o que eu queria fazer e quais eram as minhas necessidades. Nas nossas reuniões, sempre trazia ideias incríveis, que faziam muito sentido para o meu negócio — e o mais legal é que ela se preocupava em pensar em estratégias que também tivessem a ver com o meu jeito mais dinâmico e divertido de ser.</p><p>Foi uma parceria muito leve e produtiva. A gente se identificou desde o início, e eu me senti realmente compreendida e acolhida por ela! ☺️</p><p>Super recomendo o trabalho dela!”</p></blockquote></div></section>
      <section className="insights-section"><div className="shell"><p className="section-kicker">Para pensar sua presença digital</p><h2>Redes sociais e site têm papéis diferentes na decisão do cliente.</h2><div className="insights-grid"><Link href="/blog"><strong>Conteúdo e posicionamento</strong><span>Ideias para comunicar seu trabalho com mais clareza.</span></Link><Link href="/gestao-de-midias-sociais"><strong>Gestão das redes</strong><span>Conheça o processo de planejamento, criação e acompanhamento.</span></Link><Link href="/criacao-de-sites-online"><strong>Seu endereço online</strong><span>Entenda como funciona a criação de um site com domínio próprio.</span></Link></div></div></section>
      <section className="final-specialist-cta"><div className="shell"><h2>Qual parte da sua presença digital precisa de atenção agora?</h2><p>Conte o que você já tem e o que quer melhorar. A Ravyt atende clientes de todo o Brasil.</p><div><a className="button button-light" href={whatsappUrl()} target="_blank" rel="noopener noreferrer">CONVERSAR PELO WHATSAPP</a><a className="button button-ghost" href="mailto:ola@ravytdigital.com">ENVIAR UM E-MAIL</a></div></div></section>
    </main><BlogFooter />
  </>;
}
