import { BlogFooter, BlogHeader } from "@/components/BlogChrome";
import { SITE_URL } from "@/lib/site";
import { whatsappUrl } from "@/lib/contact";

const problems = ["A oferta é boa, mas a página não explica seu valor.","O conteúdo atrai pessoas, mas poucas avançam para a inscrição.","O produtor depende apenas das redes sociais.","Não existe clareza sobre visitas e conversões.","Pixels e eventos não estão configurados corretamente.","A página parece genérica e não representa a metodologia.","A mensagem não conversa com as dores e decisões dos pais."];
const steps = [["Diagnóstico","Entendemos produto, oferta, público e objetivo."],["Estratégia","Definimos estrutura, mensagem e caminho do visitante."],["Criação","Desenvolvemos copy, design e landing page."],["Integração","Configuramos formulários, cookies, pixels e eventos necessários."],["Testes e entrega","Validamos navegação, responsividade, carregamento e rastreamento."]];
const differences = ["Especialização em produtores digitais de Psicologia Parental","Copy e desenvolvimento pensados em conjunto","Design personalizado para cada oferta","Página preparada para dispositivos móveis","Configuração técnica de pixels e eventos","Comunicação ética para um segmento sensível","Estrutura baseada no nível de consciência do público","Escopo claro antes do início"];

export default function Home() {
  const schema = {"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":`${SITE_URL}/#organization`,name:"Ravyt Digital",legalName:"YTALA RAVENA DE SOUSA SILVA CABRAL CONTEUDO DIGITAL LTDA - ME",taxID:"26.114.696/0001-70",url:SITE_URL,email:"ola@ravytdigital.com",description:"Agência de landing pages e copywriting para produtores digitais de Psicologia Parental.",sameAs:["https://www.instagram.com/ravytdigital/","https://www.facebook.com/ravytdigital","https://www.linkedin.com/company/ravytdigital/"]},{"@type":"WebSite","@id":`${SITE_URL}/#website`,url:SITE_URL,name:"Ravyt Digital",inLanguage:"pt-BR",publisher:{"@id":`${SITE_URL}/#organization`}}]};
  return <><BlogHeader /><main id="conteudo" className="positioning-home">
    <section className="specialist-home-hero"><div className="shell hero-specialist-grid"><div className="hero-specialist-copy"><p className="eyebrow">Para produtores digitais de Psicologia Parental</p><h1>Landing pages e copywriting para produtores digitais de <span className="typing-text">Psicologia Parental.</span></h1><p className="hero-lead">Criamos páginas estratégicas, textos de venda e estruturas de rastreamento para apresentar sua metodologia com clareza e transformar visitantes em leads, alunos ou clientes.</p><div className="hero-actions"><a className="button button-light" href={whatsappUrl()} target="_blank" rel="noopener noreferrer" data-track="primary_cta_click">QUERO CONVERSAR SOBRE MEU PROJETO</a><a className="button button-ghost" href="#servicos">Conhecer os serviços</a></div></div></div></section>
    <section className="problem-section"><div className="shell"><p className="section-kicker">A página também precisa fazer seu trabalho</p><h2>Seu trabalho transforma famílias. Mas sua página consegue comunicar isso?</h2><div className="problem-grid">{problems.map((p,i)=><article key={p}><span>{String(i+1).padStart(2,"0")}</span><p>{p}</p></article>)}</div><p className="section-closing">A Ravyt une estrutura, copy e rastreamento para que o valor da oferta seja compreendido antes da decisão.</p></div></section>
    <section className="home-services" id="servicos"><div className="shell"><p className="section-kicker">Somente dois serviços</p><h2>Estratégia, página e mensagem para apresentar melhor seu produto digital.</h2><div className="service-duo"><article><span>01</span><h3>Landing Pages</h3><p>Criamos páginas personalizadas, responsivas e preparadas para conversão, com cookies, pixels e eventos configurados.</p><a href="/landing-pages-para-psicologia-parental">Conhecer Landing Pages →</a></article><article><span>02</span><h3>Copywriting</h3><p>Construímos uma mensagem clara para apresentar o valor da sua metodologia e conduzir o público ao próximo passo.</p><a href="/copywriting-para-psicologia-parental">Conhecer Copywriting →</a></article></div></div></section>
    <section className="process-section"><div className="shell"><p className="section-kicker">Como funciona</p><h2>Um processo claro, do diagnóstico à entrega.</h2><ol>{steps.map(([t,d],i)=><li key={t}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></div></section>
    <section className="difference-section"><div className="shell two-columns"><div><p className="section-kicker">Por que a Ravyt</p><h2>Especialização e escopo concreto.</h2><p>Não somos uma agência de marketing genérica. Trabalhamos exclusivamente com landing pages e copywriting para produtos digitais de Psicologia Parental.</p></div><div className="check-list">{differences.map(d=><p key={d}>{d}</p>)}</div></div></section>
    <section className="ethics-section"><div className="shell two-columns"><div><p className="section-kicker">Especialização</p><h2>Por que trabalhar exclusivamente com Psicologia Parental?</h2></div><div><p>Produtos deste segmento exigem comunicação acolhedora sem ser superficial, cuidado com promessas, respeito à vulnerabilidade das famílias e clareza sobre o papel do especialista.</p><p>A linguagem não deve explorar medo, culpa ou sofrimento. Também precisa diferenciar conteúdo educativo, orientação parental e atendimento clínico.</p><p><strong>A Ravyt é especialista na comunicação e na estrutura digital da oferta.</strong> Não atuamos como autoridade clínica ou serviço de saúde.</p></div></div></section>
    <section className="about-specialist" id="sobre"><div className="shell two-columns"><div><p className="section-kicker">Sobre a Ravyt</p><h2>Atendimento a produtores digitais em todo o Brasil.</h2></div><div><p>A Ravyt Digital atende produtores digitais que desenvolvem produtos voltados à Psicologia Parental.</p><p>Nosso trabalho é transformar conhecimento, método e experiência profissional em uma estrutura digital clara, confiável e preparada para conversão.</p><blockquote>“Refletir no digital a qualidade e a excelência que nossos clientes já entregam no dia a dia.”</blockquote></div></div></section>
    <section className="final-specialist-cta"><div className="shell"><h2>Sua metodologia já tem valor. Agora ela precisa de uma página capaz de demonstrá-lo.</h2><p>Conte para a Ravyt sobre seu produto digital e descubra como podemos estruturar sua landing page, sua mensagem e seu rastreamento.</p><div><a className="button button-light" href="/contato">QUERO CONVERSAR SOBRE MEU PROJETO</a><a className="button button-ghost" href={whatsappUrl()} target="_blank" rel="noopener noreferrer" data-track="primary_cta_click">QUERO CONVERSAR SOBRE MEU PROJETO</a></div></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  </main><BlogFooter /></>;
}
