import Image from 'next/image';
import Link from 'next/link';
import { projects, questions } from '@/lib/commercial';
import PortfolioPreview from '@/components/PortfolioPreview';
export function DiagnosticCTA(){return <Link className="rv-button" href="/diagnostico" data-track="primary_cta_click">Quero fortalecer minha presença no Google <span aria-hidden="true">↗</span></Link>;}
export function FinalCTA(){return <section className="rv-final"><div className="shell"><p className="rv-label">Seu próximo passo</p><h2>Seu cliente já está procurando.<br/>O que ele encontra sobre você?</h2><p>Vamos olhar para o seu negócio e entender o que merece atenção primeiro.</p><DiagnosticCTA/></div></section>;}
export function Cases(){return <div className="rv-cases">{projects.map(p=><article key={p.slug}><PortfolioPreview slug={p.slug} name={p.name}/><p className="rv-label">{p.type}</p><h3>{p.name}</h3><p>{p.text}</p></article>)}</div>;}
export function Team(){return <div className="rv-team"><article><Image src="/team/ytala-cabral-card.webp" alt="Ytala Cabral" width={320} height={464} unoptimized/><div><p className="rv-label">Ser encontrada e compreendida</p><h3>Ytala Cabral</h3><strong>SEO · Google Meu Negócio · Copy</strong><p>Pesquisa, intenção de busca e mensagem. Ytala conecta o que seu cliente procura ao que sua empresa precisa comunicar.</p></div></article><article><Image src="/team/marcio-cabral-card.webp" alt="Marcio Cabral" width={280} height={380} unoptimized/><div><p className="rv-label">Ser escolhida e contatada</p><h3>Marcio Cabral</h3><strong>UX/UI · Web Design</strong><p>Arquitetura, design e implementação. Marcio transforma a estratégia em uma experiência clara, acessível e preparada para o próximo clique.</p></div></article></div>;}
export function FAQ(){return <div className="rv-faq">{questions.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>;}
