
import {PriceText} from "@/components/i18n/Regional";
import Link from 'next/link';
import { BlogHeader, BlogFooter } from '@/components/BlogChrome';
import { DiagnosticCTA, FinalCTA } from '@/components/Commercial';
import StructuredData from '@/components/StructuredData';
import { services } from '@/lib/commercial';
import { SITE_URL } from '@/lib/site';
export default function ServicePage({slug}:{slug:string}){const s=services.find(s=>s.slug===slug)!;return <><BlogHeader/><main id="conteudo" tabIndex={-1} className="rv"><StructuredData data={{'@context':'https://schema.org','@type':'Service',name:s.name,description:s.description,url:SITE_URL+'/'+slug,provider:{'@id':SITE_URL+'/#organization'},areaServed:"Worldwide"}}/><section className="rv-page-hero"><div className="shell"><p className="rv-label">Ravyt Digital / {<PriceText>{s.name}</PriceText>}</p><h1>{<PriceText>{s.title}</PriceText>}</h1><p className="rv-lead">{<PriceText>{s.description}</PriceText>}</p><DiagnosticCTA/></div></section><section className="rv-section"><div className="shell rv-split"><div><h2>Antes da ferramenta,<br/><em>o seu negócio.</em></h2><p>{<PriceText>{s.detail}</PriceText>}</p></div><div><h2 className="rv-small-heading">O que pode fazer parte</h2><ul className="rv-deliverables">{<PriceText>{s.items.map(i=><li key={i}>{<PriceText>{i}</PriceText>}</li>)}</PriceText>}</ul><p>O escopo é definido depois de entender o ponto de partida. Você recebe uma proposta com prioridades, entregas e responsabilidades.</p></div></div></section><section className="rv-section rv-dark"><div className="shell"><p className="rv-label">Como começamos</p><h2>Entender. Priorizar. Implementar. Acompanhar.</h2><p className="rv-intro">Analisamos os canais atuais e o objetivo comercial, definimos o que resolver primeiro e combinamos como acompanhar a evolução. Não prometemos posições no Google nem volume garantido de contatos.</p><div className="rv-actions">{<PriceText>{services.filter(x=>x.slug!==slug).map(x=><Link href={'/'+x.slug} key={x.slug}>Conhecer {<PriceText>{x.name}</PriceText>} →</Link>)}</PriceText>}</div></div></section><FinalCTA/></main><BlogFooter/></>;}
