import { BlogFooter, BlogHeader } from "@/components/BlogChrome";
import { whatsappUrl, COPYWRITING_MESSAGE } from "@/lib/contact";
import { SITE_URL } from "@/lib/site";

export default function ServicePage({ kind }: { kind: "landing" | "copy" }) {
  const landing = kind === "landing";
  const title = landing ? "Criação de landing pages para produtores digitais de Psicologia Parental" : "Copywriting para produtos digitais de Psicologia Parental";
  const lead = landing ? "Páginas personalizadas para captar, inscrever, apresentar ou vender cursos, mentorias, comunidades, eventos e materiais digitais." : "Mensagens que ajudam pais e responsáveis a compreender a oferta, reconhecer o valor da metodologia e saber qual próximo passo tomar.";
  const deliverables = landing ? ["Planejamento da estrutura e jornada", "Design personalizado e desenvolvimento responsivo", "Formulários, integrações e página de agradecimento", "Cookies e consentimento por categoria", "Meta Pixel, GA4, Google Ads e Tag Manager quando os IDs forem fornecidos", "Eventos de conversão sem dados pessoais", "Desempenho, SEO técnico, Open Graph, favicon, sitemap e robots.txt"] : ["Pesquisa sobre produto, público e nível de consciência", "Proposta de valor, títulos e subtítulos", "Estrutura para página de captura ou vendas", "Benefícios e argumentos de diferenciação", "Tratamento de objeções e perguntas frequentes", "Chamadas para ação", "Revisão e adaptação de copy existente"];
  const types = landing ? ["Captura", "Inscrição", "Vendas", "Lista de espera", "Lançamento", "Evento ou workshop", "Obrigado", "Mentoria, curso ou comunidade"] : ["Clareza antes da persuasão", "Argumentos em ordem lógica", "Promessas responsáveis", "Linguagem acolhedora", "Sem exploração de medo ou culpa", "Sem garantias de resultado"];
  const path = landing ? "/landing-pages-para-psicologia-parental" : "/copywriting-para-psicologia-parental";
  const faqs = landing ? [["A página funciona no celular?","Sim. O desenvolvimento é responsivo para celular, tablet e computador."],["Os pixels estão incluídos?","Podem ser incluídos quando os IDs e acessos são fornecidos. Tags não essenciais respeitam o consentimento aplicável."],["A Ravyt gerencia anúncios?","Não. O serviço cobre a estrutura da página e a instalação técnica acordada, não a gestão de mídia."]] : [["A copy garante conversão?","Não. A copy organiza e comunica a oferta com clareza, mas não existe garantia responsável de resultado."],["Vocês revisam uma copy existente?","Sim. A revisão e adaptação podem fazer parte do escopo."],["A comunicação usa gatilhos de medo?","Não. Priorizamos clareza e persuasão responsável, sem explorar culpa, sofrimento ou vulnerabilidade familiar."]];
  const schema = {"@context":"https://schema.org","@graph":[{"@type":"Service","@id":`${SITE_URL}${path}#service`,name:title,description:lead,url:`${SITE_URL}${path}`,provider:{"@id":`${SITE_URL}/#organization`}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Início",item:SITE_URL},{"@type":"ListItem",position:2,name:landing?"Landing Pages":"Copywriting",item:`${SITE_URL}${path}`}]},{"@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
  return <><BlogHeader current="services" /><main className="specialist-page"><header className="specialist-hero"><div className="shell"><p className="section-kicker">{landing ? "Landing Pages" : "Copywriting"}</p><h1>{title}</h1><p>{lead}</p><a className="button button-light" href={whatsappUrl(landing ? undefined : COPYWRITING_MESSAGE)} target="_blank" rel="noopener noreferrer" data-track="primary_cta_click">QUERO CONVERSAR SOBRE MEU PROJETO <span aria-hidden="true">↗</span></a></div></header>
    <section className="specialist-section"><div className="shell two-columns"><div><p className="section-kicker">O que é entregue</p><h2>Estrutura e mensagem alinhadas ao objetivo da oferta.</h2></div><div className="check-list">{deliverables.map(x=><p key={x}>{x}</p>)}</div></div></section>
    <section className="specialist-section specialist-dark"><div className="shell"><p className="section-kicker">{landing ? "Tipos de página" : "Princípios da mensagem"}</p><h2>{landing ? "Uma página para cada etapa da oferta." : "Persuasão responsável em um segmento sensível."}</h2><div className="tag-grid">{types.map(x=><span key={x}>{x}</span>)}</div></div></section>
    <section className="specialist-section"><div className="shell two-columns"><div><p className="section-kicker">Processo</p><h2>Do diagnóstico à entrega.</h2></div><ol className="number-list"><li><strong>Diagnóstico</strong><span>Produto, oferta, público e objetivo.</span></li><li><strong>Estratégia</strong><span>Estrutura, mensagem e caminho de decisão.</span></li><li><strong>Criação</strong><span>Copy, design e desenvolvimento conforme o serviço.</span></li><li><strong>Validação</strong><span>Revisão, testes e ajustes antes da entrega.</span></li></ol></div></section>
    <section className="specialist-section"><div className="shell"><p className="section-kicker">Limites do escopo</p><h2>O que não está incluído.</h2><p className="wide-copy">Não oferecemos gestão de anúncios, tráfego pago, social media, produção recorrente de conteúdo, promessa de conversão ou consultoria jurídica. IDs e acessos das plataformas precisam ser fornecidos pelo cliente quando a instalação técnica fizer parte do projeto.</p></div></section>
    <section className="specialist-section"><div className="shell"><p className="section-kicker">Perguntas frequentes</p><h2>Informações para decidir com clareza.</h2><div className="faq-grid">{faqs.map(([q,a])=><article key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></div></section>
    <section className="services-cta"><div className="shell"><p>Solicite um orçamento</p><h2>Sua metodologia merece uma página e uma mensagem à altura do que entrega.</h2><a className="button button-light" href="/contato">QUERO CONVERSAR SOBRE MEU PROJETO <span aria-hidden="true">↗</span></a></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main><BlogFooter /></>;
}
