
import {PriceText} from "@/components/i18n/Regional";
import Link from 'next/link';
import { BlogHeader, BlogFooter } from "@/locales/fr/components/BlogChrome";
import { DiagnosticCTA, FinalCTA } from "@/locales/fr/components/Commercial";
import StructuredData from "@/locales/fr/components/StructuredData";
import { services } from "@/locales/fr/lib/commercial";
import { SITE_URL } from '@/lib/site';
export default function ServicePage({slug}:{slug:string}){const s=services.find(s=>s.slug===slug)!;return <><BlogHeader/><main id="conteudo" tabIndex={-1} className="rv"><StructuredData data={{'@context':'https://schema.org','@type':'Service',name:s.name,description:s.description,url:SITE_URL+"/fr/"+slug,provider:{'@id':SITE_URL+'/#organization'},areaServed:"Brésil"}}/><section className="rv-page-hero"><div className="shell"><p className="rv-label">Ravyt Digital / {<PriceText>{s.name}</PriceText>}</p><h1>{<PriceText>{s.title}</PriceText>}</h1><p className="rv-lead">{<PriceText>{s.description}</PriceText>}</p><DiagnosticCTA/></div></section><section className="rv-section"><div className="shell rv-split"><div><h2> Avant l’outil, <br/><em>  votre entreprise. </em></h2><p>{<PriceText>{s.detail}</PriceText>}</p></div><div><h2 className="rv-small-heading"> Ce qui peut être inclus </h2><ul className="rv-deliverables">{<PriceText>{s.items.map(i=><li key={i}>{<PriceText>{i}</PriceText>}</li>)}</PriceText>}</ul><p> Le périmètre est défini après compréhension du point de départ. Vous recevez une proposition avec priorités, livrables et responsabilités. </p></div></div></section><section className="rv-section rv-dark"><div className="shell"><p className="rv-label"> Comment nous commençons </p><h2> Comprendre. Prioriser. Mettre en œuvre. Suivre. </h2><p className="rv-intro"> Nous analysons les canaux actuels et l’objectif commercial, définissons les priorités et convenons du suivi de l’évolution. Nous ne promettons ni positions sur Google ni volume garanti de contacts. </p><div className="rv-actions">{<PriceText>{services.filter(x=>x.slug!==slug).map(x=><Link href={"/fr/"+x.slug} key={x.slug}> Découvrir {<PriceText>{x.name}</PriceText>} →</Link>)}</PriceText>}</div></div></section><FinalCTA/></main><BlogFooter/></>;}
