import Link from "next/link";
type Language = 'pt' | 'en' | 'fr' | 'es';
type Kind = 'blog' | 'author' | 'contact';
const content: Record<Kind, Record<Language, {title: string; paragraphs: string[]}>> = {
 blog: {
  pt:{title:'Como usar estes guias na sua decisão',paragraphs:['Comece pelo problema que você precisa resolver. Se sua empresa ainda não tem um site, os guias de criação ajudam a definir as informações, as páginas e o caminho até o contato. Se já existe um site, avalie se ele explica seus serviços, funciona no celular e permite que o visitante encontre o próximo passo. O objetivo é comparar propostas pelo que será entregue, pelas responsabilidades e pelo suporte, sem decidir apenas pelo preço.','Site, Perfil da Empresa no Google e SEO têm funções diferentes. O site organiza sua mensagem; o perfil atende às buscas locais quando o negócio é elegível; o SEO melhora a estrutura e a compreensão do conteúdo. Os artigos mostram critérios para essas escolhas. Eles não prometem posições no Google nem substituem uma análise do seu negócio. Use as perguntas dos guias para preparar seu diagnóstico.']},
  en:{title:'How to use these guides to make a decision',paragraphs:['Start with the problem you need to solve. If your business does not have a website, the website guides help you define its information, pages and path to contact. If you already have a website, check whether it explains your services, works on mobile and makes the next step clear. Compare proposals by their deliverables, responsibilities and support, rather than deciding on price alone. Use the questions in each guide to discuss the scope with your provider.','A website, Google Business Profile and SEO serve different purposes. Your website organizes your message; your profile supports local searches when your business is eligible; SEO improves content structure and understanding. These articles explain criteria for those decisions. They do not promise Google rankings or replace an assessment of your business. Read the relevant guide and bring your questions to your assessment.']},
  fr:{title:'Comment utiliser ces guides pour décider',paragraphs:['Commencez par le problème à résoudre. Si votre entreprise n’a pas de site, les guides de création vous aident à définir les informations, les pages et le parcours vers le contact. Si un site existe déjà, vérifiez qu’il présente vos services, fonctionne sur mobile et rend la prochaine étape claire. Comparez les propositions selon les livrables, les responsabilités et le support, sans décider uniquement en fonction du prix. Les questions de chaque guide vous aident à discuter du périmètre.','Le site, le Profil d’entreprise Google et le SEO remplissent des fonctions différentes. Le site organise votre message ; le profil répond aux recherches locales lorsque l’entreprise est éligible ; le SEO améliore la structure et la compréhension du contenu. Ces articles présentent des critères de décision. Ils ne promettent pas de classement sur Google et ne remplacent pas l’analyse de votre entreprise. Préparez vos questions avant le diagnostic.']},
  es:{title:'Cómo usar estas guías para tomar una decisión',paragraphs:['Empieza por el problema que necesitas resolver. Si tu empresa todavía no tiene un sitio, las guías de creación ayudan a definir la información, las páginas y el recorrido hasta el contacto. Si ya existe un sitio, revisa si explica tus servicios, funciona en móviles y permite encontrar el siguiente paso. Compara las propuestas por sus entregables, responsabilidades y soporte, sin decidir solo por el precio. Usa las preguntas de cada guía para conversar sobre el alcance.','El sitio, el Perfil de Empresa en Google y el SEO tienen funciones distintas. El sitio organiza tu mensaje; el perfil atiende las búsquedas locales cuando el negocio es elegible; el SEO mejora la estructura y la comprensión del contenido. Los artículos presentan criterios para esas decisiones. No prometen posiciones en Google ni sustituyen un análisis de tu negocio. Prepara tus preguntas para el diagnóstico.']},
 },
 author: {
  pt:{title:'Critérios editoriais e limites dos artigos',paragraphs:['Os conteúdos assinados por Ytala tratam de decisões práticas sobre sites, mensagem e presença no Google. A leitura deve ajudar você a identificar o que precisa explicar ao cliente, quais informações organizar e quais perguntas fazer antes de contratar. Exemplos apresentados nos textos são ilustrativos; não devem ser interpretados como resultados de clientes ou garantia de desempenho.','Regras de plataformas e condições de cada negócio podem mudar. Confira as referências institucionais indicadas nos artigos e verifique se a orientação se aplica ao seu caso, especialmente quanto à elegibilidade do Perfil da Empresa no Google. Uma página publicada não garante indexação nem posição de destaque. Para definir entregas, prioridades e responsabilidades, o próximo passo é analisar o ponto de partida do negócio.']},
  en:{title:'Editorial criteria and the limits of these articles',paragraphs:['Articles signed by Ytala cover practical decisions about websites, messaging and Google visibility. They help you identify what you need to explain to customers, which information to organize and which questions to ask before hiring a provider. Examples in the articles are illustrative. They should not be understood as client results or a guarantee of performance.','Platform rules and business circumstances can change. Check the institutional references included in the articles and whether the guidance applies to your case, particularly Google Business Profile eligibility. Publishing a page does not guarantee indexing or a prominent ranking. To agree on deliverables, priorities and responsibilities, assess your business’s starting point and discuss the scope before hiring.']},
  fr:{title:'Critères éditoriaux et limites des articles',paragraphs:['Les articles signés par Ytala abordent des décisions pratiques sur les sites, les messages et la visibilité sur Google. Ils vous aident à identifier ce qu’il faut expliquer aux clients, les informations à organiser et les questions à poser avant de choisir un prestataire. Les exemples sont illustratifs et ne représentent ni des résultats clients ni une garantie de performance.','Les règles des plateformes et la situation des entreprises peuvent évoluer. Consultez les références institutionnelles des articles et vérifiez que les conseils s’appliquent à votre cas, notamment l’éligibilité au Profil d’entreprise Google. Publier une page ne garantit ni son indexation ni son classement. Pour définir les livrables, les priorités et les responsabilités, analysez le point de départ de votre entreprise et discutez du périmètre.']},
  es:{title:'Criterios editoriales y límites de los artículos',paragraphs:['Los artículos firmados por Ytala tratan decisiones prácticas sobre sitios, mensajes y presencia en Google. Ayudan a identificar qué necesitas explicar al cliente, qué información organizar y qué preguntas hacer antes de contratar. Los ejemplos son ilustrativos y no deben interpretarse como resultados de clientes ni garantías de rendimiento.','Las reglas de las plataformas y las condiciones de cada negocio pueden cambiar. Consulta las referencias institucionales de los artículos y verifica si la orientación se aplica a tu caso, especialmente la elegibilidad del Perfil de Empresa en Google. Publicar una página no garantiza indexación ni posiciones destacadas. Para definir entregables, prioridades y responsabilidades, analiza el punto de partida de tu negocio y acuerda el alcance antes de contratar.']},
 },
 contact: {
  pt:{title:'O que enviar para começar',paragraphs:['Informe o nome da empresa, o serviço que você oferece, o público que deseja alcançar e a região atendida. Se já tiver site ou Perfil da Empresa no Google, envie os links. Não envie senhas ou dados de pagamento pelo formulário. Essas informações ajudam a entender seu ponto de partida e a preparar uma conversa sobre prioridades, escopo e responsabilidades.']},
  en:{title:'What to send to get started',paragraphs:['Tell us your business name, the service you offer, the audience you want to reach and the area you serve. Include links to your existing website or Google Business Profile if available. Do not send passwords or payment details through this form. This information helps us understand your starting point and prepare a discussion about priorities, scope and responsibilities.']},
  fr:{title:'Les informations utiles pour commencer',paragraphs:['Indiquez le nom de votre entreprise, vos services, le public que vous souhaitez atteindre et la zone desservie. Ajoutez les liens de votre site ou du Profil d’entreprise Google si vous en disposez. N’envoyez pas de mots de passe ni de données de paiement via le formulaire. Ces informations permettent de comprendre votre point de départ et de discuter des priorités, du périmètre et des responsabilités.']},
  es:{title:'Qué enviar para empezar',paragraphs:['Indica el nombre de tu empresa, el servicio que ofreces, el público al que quieres llegar y la región atendida. Si ya tienes sitio o Perfil de Empresa en Google, envía los enlaces. No envíes contraseñas ni datos de pago por el formulario. Esta información ayuda a entender tu punto de partida y a preparar una conversación sobre prioridades, alcance y responsabilidades.']},
 },
};
export default function PageGuidance({kind,lang='pt'}:{kind:Kind;lang?:Language}) {
 const copy=content[kind][lang],prefix=lang==='pt'?'':'/'+lang;
 return <section className="rv-section"><div className="shell"><h2>{copy.title}</h2>{copy.paragraphs.map(text=><p key={text}>{text}</p>)}{kind==='blog'&&<nav aria-label={copy.title}><Link href={prefix+'/sites'}>Sites</Link> · <Link href={prefix+'/google-meu-negocio'}>Google</Link> · <Link href={prefix+'/seo'}>SEO</Link></nav>}</div></section>;
}
