'use client';
import Link from 'next/link';
import {PRICING,money} from '@/lib/i18n/regional';
import {useRegional} from './Regional';
const copy={
 pt:{name:'PRESENÇA DIGITAL COMPLETA',intro:'Seu negócio no Google com site profissional, SEO e acompanhamento contínuo.',month:'/mês',equivalent:'Equivalente mensal do plano anual de',annual:'Plano anual de',duration:'com serviços e acompanhamento durante 12 meses.',daily:'por dia para sua empresa construir e manter uma presença digital profissional.',less:'Menos de',approx:'Equivalente diário aproximado:',day:'/dia',info:'Os equivalentes mensal e diário são informativos. A contratação é anual.',setup:'Sem taxa de implantação',payment:'Cartão de crédito, conforme as condições da proposta.',pix:'Pix, cartão de crédito ou boleto, conforme as condições da proposta.',bonus:'Bônus exclusivo para clientes no Brasil: Cartão NFC de Avaliação do Google.',cancel:'Você tem 7 dias para desistir da contratação.',cta:'QUERO MINHA PRESENÇA DIGITAL',benefits:['Implantação da presença digital','Criação e otimização do Perfil da Empresa no Google, para negócios elegíveis','Site profissional One Page, responsivo e otimizado','Estrutura inicial de SEO','Melhorias contínuas de SEO dentro do escopo contratado','Domínio e hospedagem incluídos','Manutenção durante os 12 meses','Atualizações e suporte conforme o escopo']},
 en:{name:'COMPLETE DIGITAL PRESENCE',intro:'Your business on Google with a professional website, SEO and ongoing support.',month:'/month',equivalent:'Monthly equivalent of the annual plan:',annual:'Annual plan:',duration:'with services and ongoing support for 12 months.',daily:'a day for your business to build and maintain a professional digital presence.',less:'Less than',approx:'Approximate daily equivalent:',day:'/day',info:'Monthly and daily equivalents are for information only. This is an annual subscription.',setup:'No setup fee',payment:'Credit card, subject to the proposal’s conditions.',pix:'Pix, credit card or boleto, subject to the proposal’s conditions.',bonus:'Exclusive bonus for clients in Brazil: Google Review NFC Card.',cancel:'You have 7 days to withdraw from the purchase.',cta:'BUILD MY DIGITAL PRESENCE',benefits:['Digital presence setup','Google Business Profile creation and optimization for eligible businesses','Professional, responsive and optimized One Page website','Initial SEO structure','Ongoing SEO improvements within the agreed scope','Domain and hosting included','Maintenance throughout the 12 months','Updates and support within the agreed scope']},
 fr:{name:'PRÉSENCE NUMÉRIQUE COMPLÈTE',intro:'Votre entreprise sur Google avec un site professionnel, du SEO et un accompagnement continu.',month:'/mois',equivalent:'Équivalent mensuel du forfait annuel de',annual:'Forfait annuel de',duration:'avec des services et un accompagnement pendant 12 mois.',daily:'par jour pour construire et maintenir une présence numérique professionnelle.',less:'Moins de',approx:'Équivalent journalier approximatif :',day:'/jour',info:'Les équivalents mensuel et journalier sont indicatifs. L’abonnement est annuel.',setup:'Sans frais de mise en place',payment:'Carte bancaire, selon les conditions de la proposition.',pix:'Pix, carte bancaire ou boleto, selon les conditions de la proposition.',bonus:'Bonus exclusif pour les clients au Brésil : carte NFC pour les avis Google.',cancel:'Vous disposez de 7 jours pour vous rétracter.',cta:'DÉVELOPPER MA PRÉSENCE EN LIGNE',benefits:['Mise en place de la présence numérique','Création et optimisation du Profil d’entreprise Google pour les entreprises éligibles','Site professionnel One Page, responsive et optimisé','Structure initiale de SEO','Améliorations continues du SEO dans le périmètre convenu','Domaine et hébergement inclus','Maintenance pendant les 12 mois','Mises à jour et support selon le périmètre convenu']},
 es:{name:'PRESENCIA DIGITAL COMPLETA',intro:'Tu negocio en Google con un sitio profesional, SEO y acompañamiento continuo.',month:'/mes',equivalent:'Equivalente mensual del plan anual de',annual:'Plan anual de',duration:'con servicios y acompañamiento durante 12 meses.',daily:'al día para construir y mantener una presencia digital profesional.',less:'Menos de',approx:'Equivalente diario aproximado:',day:'/día',info:'Los equivalentes mensual y diario son informativos. La contratación es anual.',setup:'Sin tarifa de implementación',payment:'Tarjeta de crédito, según las condiciones de la propuesta.',pix:'Pix, tarjeta de crédito o boleto, según las condiciones de la propuesta.',bonus:'Bono exclusivo para clientes en Brasil: tarjeta NFC de reseñas de Google.',cancel:'Tienes 7 días para desistir de la contratación.',cta:'MEJORAR MI PRESENCIA DIGITAL',benefits:['Implementación de la presencia digital','Creación y optimización del Perfil de Empresa en Google para negocios elegibles','Sitio profesional One Page, adaptable y optimizado','Estructura inicial de SEO','Mejoras continuas de SEO dentro del alcance contratado','Dominio y alojamiento incluidos','Mantenimiento durante los 12 meses','Actualizaciones y soporte según el alcance']}
};
export function CompactPrice(){const {currency,lang}=useRegional();const c=copy[lang as keyof typeof copy]??copy.pt;return <>{money(PRICING.annual/PRICING.months,currency,lang)}{c.month} — {c.equivalent} {money(PRICING.annual,currency,lang)}.</>;}
export function PlanOffer(){const {currency,lang,country}=useRegional();const c=copy[lang as keyof typeof copy]??copy.pt;const format=(amount:number)=>money(amount,currency,lang);return <div className="rv-offer-price" data-pricing-currency={currency}>
 <p className="rv-label">{c.name}</p><p>{c.intro}</p>
 <strong className="rv-price-main"><span>{format(PRICING.annual/PRICING.months)}</span><small>{c.month}</small></strong>
 <p className="rv-price-annual">{c.equivalent} <span>{format(PRICING.annual)}</span>.</p>
 <p>{c.annual} {format(PRICING.annual)}, {c.duration}</p>
 <p className="rv-price-daily">{c.approx} <span>{format(PRICING.annual/PRICING.days)}{c.day}</span>.</p>
 <small>{c.info}</small><span className="rv-plan-perk">{c.setup}</span>
 <ul className="rv-plan-services">{c.benefits.map(item=><li key={item}>{item}</li>)}</ul>
 <small>{country==='BR'?c.pix:c.payment}</small><small>{c.cancel}</small>
 <Link className="rv-button" href={(lang==='pt'?'':'/'+lang)+'/diagnostico'} data-track="primary_cta_click">{c.cta}<span aria-hidden="true">↗</span></Link>
 </div>;}

export function PlanPreview(){const {lang}=useRegional();const c={pt:['Site profissional em todos os dispositivos','Demonstração ilustrativa de um site profissional em desktop.'],en:['A professional website on every device','Illustrative demonstration of a professional desktop website.'],fr:['Un site professionnel sur tous les appareils','Démonstration illustrative d’un site professionnel sur ordinateur.'],es:['Un sitio profesional en todos los dispositivos','Demostración ilustrativa de un sitio profesional en ordenador.']}[lang]??['Professional website','Website demonstration'];return <aside className="rv-nfc-preview"><img src="/mockups/site-desktop.webp" width="1536" height="1024" loading="lazy" decoding="async" alt={c[1]}/><h3>{c[0]}</h3><p className="rv-demo-note">{c[1]}</p></aside>;}
