export const services = [
 {slug:'seo',name:'SEO',title:'Quem procura sua solução consegue encontrar você?',description:'SEO estratégico para aproximar sua empresa de quem já procura pelo que ela oferece.',detail:'Aparecer pelo nome é um começo. A oportunidade está em ser encontrado pelo serviço, pela dúvida e pela necessidade que levam alguém a comprar.',items:['Pesquisa de intenção de busca e concorrência','Arquitetura e conteúdo das páginas de serviço','SEO técnico, indexação e acompanhamento']},
 {slug:'google-meu-negocio',name:'Presença Local',title:'Perto do cliente. Presente na hora da escolha.',description:'Google Meu Negócio e SEO local para empresas que precisam ser encontradas no Google e no Maps.',detail:'Seu Perfil da Empresa no Google — antes chamado Google Meu Negócio — pode ser o primeiro contato de alguém com seu negócio. Serviços, horários e avaliações precisam contar a mesma história.',items:['Análise de elegibilidade e configuração do perfil','Categorias, serviços e informações consistentes','Orientação para avaliações e acompanhamento local']},
 {slug:'sites',name:'Sites Estratégicos',title:'Depois do clique, começa a decisão.',description:'Sites com UX/UI, copy e SEO técnico para transformar descoberta em compreensão, confiança e contato.',detail:'Seu site explica o que você resolve, para quem e qual é o próximo passo? Construímos essa jornada com conteúdo claro, boa experiência no celular e uma estrutura que pode evoluir.',items:['Arquitetura, UX/UI e copy orientadas à decisão','Desenvolvimento responsivo, acessibilidade e performance','Formulários, WhatsApp e mensuração conforme o escopo']}
];
export const projects = [
 {name:'Odonto Premium',type:'Site institucional',image:'odonto-premium',url:'https://site-odonto-premium.ravytdigital.workers.dev',text:'Apresentação de serviços de saúde em uma experiência digital focada em clareza e contato.'},
 {name:'Capoeira Haute-Savoie',type:'Site institucional',image:'capoeira-haute-savoie',url:'https://site-capoeira-haute-savoie.ravytdigital.workers.dev',text:'Um endereço próprio para apresentar a escola e aproximar novos alunos.'},
 {name:'Excel no Agro',type:'Página de vendas',image:'excel-no-agro',url:'https://site-excel-no-agro.ravytdigital.workers.dev',text:'Conteúdo e hierarquia visual organizados para apresentar uma oferta educacional.'}
];
export const questions = [
 ['Por onde minha empresa deve começar?','Pelo diagnóstico. Olhamos como sua empresa aparece, o que comunica e como recebe contatos. A recomendação parte do problema prioritário: presença local, SEO, site ou uma combinação dessas frentes.'],
 ['Vocês garantem o primeiro lugar no Google?','Não. A posição depende de concorrência, localização, relevância e critérios do Google. Trabalhamos a estrutura e o conteúdo que podemos melhorar, com acompanhamento e expectativas claras.'],
 ['Em quanto tempo o SEO traz resultado?','SEO é um trabalho progressivo. O prazo varia conforme o ponto de partida, o mercado e a execução. O diagnóstico orienta prioridades e indicadores; não prometemos um prazo único para todas as empresas.'],
 ['Preciso trocar meu site?','Nem sempre. Primeiro avaliamos a estrutura, a mensagem, a experiência e as integrações atuais. Podemos recomendar melhorias no que já existe quando isso atende ao objetivo.'],
 ['Quanto custa e o que está incluído?','O investimento depende do escopo, do estado atual dos canais e do acompanhamento necessário. Após entender o negócio, apresentamos uma proposta com entregas, responsabilidades e condições.'],
 ['Vocês também trabalham com redes sociais?','As redes entram na etapa de expansão, conforme a necessidade do negócio e o escopo acordado. A prioridade é organizar busca, presença local e conversão antes de ampliar novas frentes.'],
 ['Como funciona o diagnóstico?','Você compartilha o nome da empresa, a região e os canais atuais. A conversa continua pelo WhatsApp para entendermos o contexto e combinarmos a análise. O formulário não gera uma auditoria automática.']
];
