export type ChecklistCopy = {
  title: string; description: string; intro: string; label: string;
  groups: string[]; items: [string, string][]; progress: string; print: string; reset: string;
  note: string; sources: string; sourceLabels: string[]; cite: string; permission: string;
  cta: string; ctaBody: string; ctaLink: string; cardTitle: string; cardBody: string; cardLink: string;
};
export const checklistPath = '/recursos/checklist-presenca-google';
export const checklistCopy: Record<string, ChecklistCopy> = {
  pt: {
    title:'Checklist de presença no Google', description:'Checklist gratuito para revisar Perfil da Empresa, site e SEO. Marque os pontos conferidos, consulte fontes oficiais e imprima sua revisão.',
    label:'Recurso gratuito · Ravyt Digital', intro:'Seu cliente consegue encontrar sua empresa, entender o que você oferece e entrar em contato? Confira 12 pontos e identifique o que precisa de atenção.',
    groups:['01 / Perfil da Empresa','02 / Site e contato','03 / Conteúdo e referências'],
    items:[
      ['Elegibilidade antes de criar o perfil','Confirme se o negócio recebe clientes presencialmente ou atende no endereço deles. Negócios exclusivamente online não são elegíveis. Se não for elegível, concentre o trabalho no site e na busca orgânica.'],
      ['Identidade e categoria corretas','Use o nome real do negócio e categorias que descrevam sua atividade. Confira telefone, horários e endereço ou área de atendimento; não adicione palavras-chave artificiais ao nome.'],
      ['Site vinculado e informações coerentes','Abra o link do site no perfil e confira se funciona. Compare os dados de contato e atendimento nas duas páginas.'],
      ['Fotos reais e avaliações autênticas','Apresente fotos atuais e responda às avaliações. Convide clientes a avaliar sem recompensas e sem pedir somente avaliações positivas.'],
      ['Serviços e público claros','Na primeira tela do site, explique o que faz, para quem e como atende. Um visitante precisa entender a oferta sem adivinhar.'],
      ['Contato funcionando no celular','Teste os botões de WhatsApp, telefone e formulários em um celular. Confira se levam ao contato correto e se o formulário confirma o envio.'],
      ['Páginas acessíveis aos buscadores','Confira as páginas principais no Search Console. Investigue bloqueios por robots.txt, noindex e erros; enviar um sitemap não garante indexação.'],
      ['Títulos, navegação e experiência','Use títulos descritivos e links internos claros. Verifique leitura no celular, contraste, imagens e velocidade; evite texto ou botões sobrepostos.'],
      ['Conteúdo que resolve uma dúvida','Publique respostas úteis sobre os serviços, com exemplos e fontes. Evite páginas quase iguais que trocam apenas o nome da cidade.'],
      ['Provas identificadas com transparência','Mostre projetos e entregas verificáveis. Diferencie demonstrações de clientes reais e não atribua resultados de vendas ou posições sem evidência.'],
      ['Referências relevantes, sem atalhos','Busque menções editoriais e diretórios que ajudem seu público. Evite pacotes de links e comentários em massa; links patrocinados devem ser qualificados.'],
      ['Medição além das posições','Registre contatos, visitas orgânicas e visitas vindas de outros sites. Compare períodos e contexto antes de atribuir uma mudança a uma ação de SEO.'],
    ],
    progress:'pontos conferidos', print:'Imprimir / salvar em PDF', reset:'Limpar marcações',
    note:'Esta é uma revisão manual, não uma auditoria automática nem uma nota de SEO. As marcações ficam apenas nesta página e são apagadas ao recarregar. Confira os pontos do perfil somente se o negócio for elegível. Nenhuma posição no Google é garantida.',
    sources:'Fontes para conferir as orientações', sourceLabels:['Diretrizes do Perfil da Empresa','Classificação local no Google','Fundamentos da Pesquisa Google','Políticas de spam e links','Políticas sobre avaliações'],
    cite:'Como citar este recurso', permission:'Você pode compartilhar o endereço e citar trechos com atribuição à Ravyt Digital. Ao referenciar o checklist, use o link desta página para que o leitor consulte a versão atual.',
    cta:'Encontrou pontos que precisam de atenção?', ctaBody:'Leve sua revisão para uma conversa sobre a estrutura de Google, site e SEO do seu negócio.', ctaLink:'Conversar sobre minha presença digital →',
    cardTitle:'Sua presença no Google, ponto por ponto.', cardBody:'Use nosso checklist gratuito para revisar perfil, site, contato e referências. Você pode marcar os itens e imprimir sua revisão.', cardLink:'Abrir checklist gratuito →',
  },
  en: {
    title:'Google presence checklist', description:'Free checklist to review your Business Profile, website and SEO. Check each item, consult official sources and print your review.',
    label:'Free resource · Ravyt Digital', intro:'Can customers find your business, understand your services and contact you? Review 12 points to identify what needs attention.',
    groups:['01 / Business Profile','02 / Website and contact','03 / Content and references'],
    items:[
      ['Check eligibility first','Confirm whether the business receives customers in person or visits them at their address. Online-only businesses are not eligible. If ineligible, focus on your website and organic search.'],
      ['Accurate identity and category','Use the real business name and categories describing its activity. Check the phone, hours and address or service area; do not add artificial keywords to the name.'],
      ['Working website link and consistent information','Open the website link in the profile and check that it works. Compare contact details and service information on both pages.'],
      ['Real photos and authentic reviews','Show current photos and reply to reviews. Invite customers to review without rewards and without asking only for positive reviews.'],
      ['Clear services and audience','Explain what you do, who you serve and how you work in the first screen of your website. Visitors should understand your offer without guessing.'],
      ['Contact that works on mobile','Test WhatsApp buttons, phone links and forms on a phone. Check that they reach the right contact and that the form confirms submission.'],
      ['Pages accessible to search engines','Check key pages in Search Console. Investigate robots.txt blocks, noindex and errors; submitting a sitemap does not guarantee indexing.'],
      ['Titles, navigation and usability','Use descriptive titles and clear internal links. Check mobile readability, contrast, images and speed; avoid overlapping text or buttons.'],
      ['Content that answers a question','Publish useful answers about your services, with examples and sources. Avoid near-identical pages that only change the city name.'],
      ['Clearly identified evidence','Show verifiable projects and deliverables. Distinguish demos from real clients and do not claim sales or ranking results without evidence.'],
      ['Relevant references without shortcuts','Seek editorial mentions and directories useful to your audience. Avoid link packages and mass comments; sponsored links must be qualified.'],
      ['Measurement beyond rankings','Record enquiries, organic visits and visits from other websites. Compare periods and context before attributing a change to an SEO action.'],
    ],
    progress:'points reviewed', print:'Print / save as PDF', reset:'Clear selections',
    note:'This is a manual review, not an automated audit or an SEO score. Selections stay on this page only and clear when you reload. Review profile items only if the business is eligible. No Google position is guaranteed.',
    sources:'Sources to verify this guidance', sourceLabels:['Business Profile guidelines','Local ranking on Google','Google Search Essentials','Spam and link policies','Review policies'],
    cite:'How to cite this resource', permission:'You may share this URL and quote excerpts with attribution to Ravyt Digital. Link to this page when referencing the checklist so readers can consult the current version.',
    cta:'Found points that need attention?', ctaBody:'Bring your review to a conversation about your business’s Google, website and SEO structure.', ctaLink:'Discuss my digital presence →',
    cardTitle:'Your Google presence, point by point.', cardBody:'Use our free checklist to review your profile, website, contact and references. Check the items and print your review.', cardLink:'Open free checklist →',
  },
  fr: {
    title:'Checklist de présence sur Google', description:'Checklist gratuite pour vérifier votre profil d’entreprise, votre site et votre SEO. Cochez les points, consultez les sources officielles et imprimez votre bilan.',
    label:'Ressource gratuite · Ravyt Digital', intro:'Vos clients peuvent-ils trouver votre entreprise, comprendre vos services et vous contacter ? Vérifiez 12 points pour repérer les améliorations à apporter.',
    groups:['01 / Profil d’entreprise','02 / Site et contact','03 / Contenu et références'],
    items:[
      ['Vérifier d’abord l’éligibilité','Confirmez que l’entreprise reçoit ses clients en personne ou se rend chez eux. Les entreprises exclusivement en ligne ne sont pas éligibles. Sinon, concentrez-vous sur le site et la recherche organique.'],
      ['Identité et catégorie exactes','Utilisez le vrai nom de l’entreprise et des catégories décrivant son activité. Vérifiez téléphone, horaires et adresse ou zone desservie ; n’ajoutez pas de mots-clés artificiels au nom.'],
      ['Lien du site et informations cohérentes','Ouvrez le lien du site depuis le profil et vérifiez son fonctionnement. Comparez les coordonnées et les informations de service sur les deux pages.'],
      ['Photos réelles et avis authentiques','Présentez des photos actuelles et répondez aux avis. Invitez les clients à donner leur avis sans récompense et sans solliciter uniquement des avis positifs.'],
      ['Services et public clairement définis','Expliquez ce que vous faites, pour qui et comment dès le premier écran du site. Le visiteur doit comprendre votre offre sans devoir la deviner.'],
      ['Contact fonctionnel sur mobile','Testez les boutons WhatsApp, les liens téléphoniques et les formulaires sur un téléphone. Vérifiez le destinataire et la confirmation d’envoi du formulaire.'],
      ['Pages accessibles aux moteurs','Vérifiez les pages principales dans Search Console. Recherchez les blocages robots.txt, noindex et les erreurs ; envoyer un sitemap ne garantit pas l’indexation.'],
      ['Titres, navigation et ergonomie','Utilisez des titres descriptifs et des liens internes clairs. Vérifiez la lecture sur mobile, le contraste, les images et la vitesse ; évitez les textes ou boutons superposés.'],
      ['Contenu qui répond à une question','Publiez des réponses utiles sur vos services, avec exemples et sources. Évitez les pages presque identiques où seul le nom de la ville change.'],
      ['Preuves présentées avec transparence','Présentez des projets et livrables vérifiables. Distinguez les démonstrations des vrais clients et n’annoncez pas de résultats de vente ou de classement sans preuve.'],
      ['Références pertinentes sans raccourcis','Recherchez des mentions éditoriales et des annuaires utiles à votre public. Évitez les lots de liens et les commentaires en masse ; les liens sponsorisés doivent être qualifiés.'],
      ['Mesurer au-delà des positions','Suivez les demandes, visites organiques et visites provenant d’autres sites. Comparez les périodes et le contexte avant d’attribuer un changement à une action SEO.'],
    ],
    progress:'points vérifiés', print:'Imprimer / enregistrer en PDF', reset:'Effacer les sélections',
    note:'Il s’agit d’une vérification manuelle, pas d’un audit automatique ni d’une note SEO. Les sélections restent uniquement sur cette page et disparaissent au rechargement. Vérifiez les points du profil seulement si l’entreprise est éligible. Aucune position sur Google n’est garantie.',
    sources:'Sources pour vérifier ces conseils', sourceLabels:['Consignes du profil d’entreprise','Classement local sur Google','Essentiels de la recherche Google','Règles sur le spam et les liens','Règles relatives aux avis'],
    cite:'Comment citer cette ressource', permission:'Vous pouvez partager cette adresse et citer des extraits en les attribuant à Ravyt Digital. Ajoutez un lien vers cette page pour que les lecteurs consultent la version actuelle.',
    cta:'Des points demandent votre attention ?', ctaBody:'Utilisez votre bilan pour discuter de la structure Google, site et SEO de votre entreprise.', ctaLink:'Discuter de ma présence numérique →',
    cardTitle:'Votre présence sur Google, point par point.', cardBody:'Vérifiez gratuitement votre profil, site, contact et références. Cochez les points et imprimez votre bilan.', cardLink:'Ouvrir la checklist gratuite →',
  },
  es: {
    title:'Checklist de presencia en Google', description:'Checklist gratuita para revisar tu Perfil de Empresa, sitio y SEO. Marca los puntos, consulta fuentes oficiales e imprime tu revisión.',
    label:'Recurso gratuito · Ravyt Digital', intro:'¿Tus clientes pueden encontrar tu empresa, entender tus servicios y contactarte? Revisa 12 puntos para identificar qué necesita atención.',
    groups:['01 / Perfil de Empresa','02 / Sitio y contacto','03 / Contenido y referencias'],
    items:[
      ['Comprobar primero la elegibilidad','Confirma si el negocio recibe clientes en persona o los atiende en sus domicilios. Los negocios exclusivamente online no son elegibles. Si no es elegible, céntrate en el sitio y la búsqueda orgánica.'],
      ['Identidad y categoría correctas','Usa el nombre real y categorías que describan la actividad. Comprueba teléfono, horarios y dirección o área de servicio; no añadas palabras clave artificiales al nombre.'],
      ['Enlace del sitio e información coherente','Abre el enlace del sitio desde el perfil y comprueba que funciona. Compara los datos de contacto y atención en ambas páginas.'],
      ['Fotos reales y reseñas auténticas','Muestra fotos actuales y responde a las reseñas. Invita a clientes a opinar sin recompensas y sin solicitar únicamente reseñas positivas.'],
      ['Servicios y público claros','Explica qué haces, para quién y cómo atiendes en la primera pantalla del sitio. El visitante debe entender la oferta sin adivinar.'],
      ['Contacto que funciona en el móvil','Prueba botones de WhatsApp, enlaces telefónicos y formularios desde un móvil. Comprueba el destinatario y que el formulario confirme el envío.'],
      ['Páginas accesibles a los buscadores','Revisa las páginas principales en Search Console. Investiga bloqueos por robots.txt, noindex y errores; enviar un sitemap no garantiza la indexación.'],
      ['Títulos, navegación y experiencia','Usa títulos descriptivos y enlaces internos claros. Comprueba lectura en móvil, contraste, imágenes y velocidad; evita textos o botones superpuestos.'],
      ['Contenido que resuelve una duda','Publica respuestas útiles sobre los servicios, con ejemplos y fuentes. Evita páginas casi idénticas que solo cambian el nombre de la ciudad.'],
      ['Pruebas identificadas con transparencia','Muestra proyectos y entregas verificables. Distingue demostraciones de clientes reales y no atribuyas resultados de ventas o posiciones sin pruebas.'],
      ['Referencias relevantes sin atajos','Busca menciones editoriales y directorios útiles para tu público. Evita paquetes de enlaces y comentarios masivos; los enlaces patrocinados deben calificarse.'],
      ['Medición más allá de las posiciones','Registra consultas, visitas orgánicas y visitas desde otros sitios. Compara periodos y contexto antes de atribuir un cambio a una acción SEO.'],
    ],
    progress:'puntos revisados', print:'Imprimir / guardar en PDF', reset:'Borrar selecciones',
    note:'Es una revisión manual, no una auditoría automática ni una puntuación SEO. Las selecciones permanecen solo en esta página y se borran al recargar. Revisa los puntos del perfil solo si el negocio es elegible. No se garantiza ninguna posición en Google.',
    sources:'Fuentes para comprobar las orientaciones', sourceLabels:['Directrices del Perfil de Empresa','Clasificación local en Google','Fundamentos de la Búsqueda de Google','Políticas de spam y enlaces','Políticas sobre reseñas'],
    cite:'Cómo citar este recurso', permission:'Puedes compartir esta dirección y citar fragmentos con atribución a Ravyt Digital. Enlaza esta página para que el lector consulte la versión actual.',
    cta:'¿Encontraste puntos que necesitan atención?', ctaBody:'Lleva tu revisión a una conversación sobre la estructura de Google, sitio y SEO de tu negocio.', ctaLink:'Hablar sobre mi presencia digital →',
    cardTitle:'Tu presencia en Google, punto por punto.', cardBody:'Usa nuestra checklist gratuita para revisar perfil, sitio, contacto y referencias. Marca los puntos e imprime tu revisión.', cardLink:'Abrir checklist gratuita →',
  },
};
export const checklistSources = [
  'https://support.google.com/business/answer/3038177',
  'https://support.google.com/business/answer/7091',
  'https://developers.google.com/search/docs/essentials',
  'https://developers.google.com/search/docs/essentials/spam-policies',
  'https://support.google.com/contributionpolicy/answer/7400114',
];
