import {ExchangeNote} from "@/components/i18n/Regional";

import {PriceText} from "@/components/i18n/Regional";
import Link from 'next/link';
import { BlogHeader, BlogFooter } from "@/locales/en/components/BlogChrome";
import { Cases, DiagnosticCTA, FAQ, Team } from "@/locales/en/components/Commercial";
import ScrollReveal from "@/locales/en/components/ScrollReveal";
import { pageMetadata } from "@/locales/en/lib/metadata";
export const metadata = pageMetadata({title:"Google + Website + SEO for Businesses",description:"Digital presence with a professional website, maintenance and SEO. A single annual plan of 597, payable by card or boleto, with the same Google, website and SEO services.",alternates:{canonical:"/en"}});
const pillars=[
  {name:'Google',title:"Google Business Profile and local presence.",body:"We organize and optimize your Google Business Profile, when eligible, with consistent information for local searches.",items:["Business setup and information","Optimizations for local searches","Ongoing improvements"],href:"/en/google-meu-negocio"},
  {name:"Website",title:"Professional Website Creation.",body:"We create and maintain a professional website that presents your business, inspires trust and makes contact easier.",items:["Website and domain creation","Hosting and updates","Ongoing support"],href:"/en/sites"},
  {name:'SEO',title:"Local SEO and search structure.",body:"We work on the website’s structure and pages so search engines can better understand your business.",items:["Technical SEO structure","Page optimization","Monitoring and improvements"],href:"/en/seo"}
];
export default function Home(){return <><BlogHeader transparent/><main id="conteudo" tabIndex={-1} className="rv"><ScrollReveal/>
<section className="rv-hero"><video className="rv-hero-video" autoPlay muted loop playsInline preload="metadata" poster="/hero/ravyt-poster-20260927.webp" aria-hidden="true"><source src="/hero-video-20260927" type="video/mp4" /></video><div className="rv-hero-shade" aria-hidden="true"/><div className="shell rv-hero-inner"><p className="rv-label"> Google • Website • SEO </p><h1> Google + Website + SEO for businesses <em>  worldwide. </em></h1><p className="rv-lead"> Your business needs to be found when customers search. We create your website and work on your Google presence to turn searches into opportunities. </p><div className="rv-actions"><DiagnosticCTA/><a href="#como-funciona"> Understand how it works ↓ </a></div><p className="rv-hero-note"><PriceText> Single annual plan: R$ 597,00 · Pix, card or boleto </PriceText></p></div><div className="shell rv-hero-bottom"><span> Being found is the beginning. </span><span> Being chosen is the next step. </span></div></section>
<section className="rv-section rv-problem" data-reveal><div className="shell"><p className="rv-label"> The demand already exists </p><h2> When someone looks for what you offer, do they find your business <em>  or your competitor? </em></h2><p className="rv-intro"> Being online does not mean being found. Your business needs to appear in searches, inspire trust and offer a simple way for customers to get in touch. </p><ol className="rv-path"><li> Research </li><li> Finds </li><li> Trusts </li><li> Gets in touch </li></ol></div></section>
<section className="rv-section rv-dark" data-reveal><div className="shell"><p className="rv-label"> The Ravyt solution </p><h2> A complete structure to help your business <em>  grow on Google. </em></h2><p className="rv-intro"> We bring local presence, a professional website and SEO together in a single strategy to build and maintain a stronger digital presence for your business. </p></div></section>
<section className="rv-section rv-services" id="servicos"><div className="shell"><p className="rv-label" data-reveal> Three pillars. One offer. </p><h2 data-reveal> Google + Website + SEO. </h2><div className="rv-pillars">{<PriceText>{pillars.map((p,i)=><article data-reveal key={p.name}><span className="rv-step">0{<PriceText>{i+1}</PriceText>} / {<PriceText>{p.name}</PriceText>}</span><h3>{<PriceText>{p.title}</PriceText>}</h3><p>{<PriceText>{p.body}</PriceText>}</p><ul>{<PriceText>{p.items.map(item=><li key={item}>{<PriceText>{item}</PriceText>}</li>)}</PriceText>}</ul><Link href={p.href}> Explore {<PriceText>{p.name}</PriceText>} ↗</Link></article>)}</PriceText>}</div></div></section>
<section className="rv-section rv-connection" id="como-funciona" data-reveal><div className="shell"><p className="rv-label"> How everything connects </p><h2> A structure working <em>  together. </em></h2><p className="rv-intro"> The Business Profile helps customers find you. The website explains your services and makes contact easier. SEO strengthens this structure in search. </p><div className="rv-flow"><span>Google</span><span> Website </span><span> Contact </span></div><p className="rv-flow-base"> SEO strengthens every step. </p></div></section>
<section className="rv-section rv-showcase" id="presenca-na-pratica"><div className="shell"><p className="rv-label" data-reveal> Your digital presence in practice </p><h2 data-reveal> See what your customer <em>  will find. </em></h2><p className="rv-intro" data-reveal> A profile that presents your business. A website that explains your services. A simple way to get in touch. </p><div className="rv-showcase-grid"><figure data-reveal><img src="/mockups/perfil-google.webp" alt="Fictional demonstration of Clínica Aurora’s Google Business Profile on a phone" width="1122" height="1402" loading="lazy" decoding="async"/><figcaption><span className="rv-step">01 / Google</span><h3> Your business in search. </h3><p> Information, services and photos together in the Business Profile, when the business is eligible. </p></figcaption></figure><figure data-reveal><img src="/mockups/site-mobile.webp" alt="Demonstration of Clínica Aurora’s professional website adapted for phones" width="1122" height="1402" loading="lazy" decoding="async"/><figcaption><span className="rv-step"> 02 / Website on mobile </span><h3> From interest to contact. </h3><p> Clear services and an easy-to-find contact button, even on a small screen. </p></figcaption></figure><figure className="rv-showcase-desktop" data-reveal><img src="/mockups/site-desktop.webp" alt="Demonstration of Clínica Aurora’s website on a desktop monitor" width="1536" height="1024" loading="lazy" decoding="async"/><figcaption><span className="rv-step"> 03 / Website on desktop </span><h3> A presentation worthy of your business. </h3><p> The same identity, with an experience adapted to every screen. </p></figcaption></figure></div><p className="rv-nfc-region"><strong>The NFC card is available only to clients in Brazil.</strong></p><p className="rv-demo-note"> Illustrative examples featuring the fictional business Clínica Aurora. The project is customized for your business. </p></div></section>
<section className="rv-section rv-included" data-reveal><div className="shell rv-split"><div><p className="rv-label"> Everything included </p><h2> Worldwide Remote Service. <em> A structure for your digital presence. </em></h2><p> An end-to-end managed structure, without having to handle hosting, maintenance and optimization on your own. </p></div><ul className="rv-deliverables"><li> Google Business Profile, when eligible </li><li> Optimizations for local searches </li><li> Professional website and domain </li><li> Hosting, updates and support </li><li> SEO structure and ongoing optimizations </li></ul></div></section>
<section className="rv-section rv-offer" id="investimento" data-reveal><div className="shell rv-offer-grid rv-single-plan"><div><p className="rv-label"> Digital presence plan </p><h2> Google + Website + SEO. <em> Your digital presence for one year. </em></h2></div><div className="rv-plan-visual-layout"><div className="rv-plan-list"><div className="rv-offer-price"><p> Single annual plan </p><strong><PriceText>R$ 597,00 </PriceText><small> /year </small></strong><ExchangeNote/><span className="rv-plan-perk"> No setup fee </span><small> <PriceText>Pay by Pix, credit card or boleto. </PriceText></small><ul className="rv-plan-services"><li> Digital presence setup </li><li> Professional one-page website </li><li> Free domain and hosting </li><li> Maintenance </li><li> SEO improvements </li><li> Google Business Profile creation and optimization </li><li> Updates and support </li></ul><span className="rv-plan-bonus"><strong> Bonus included </strong> Google Review NFC Card (available only in Brazil) </span><small> You have 7 days to withdraw from the service agreement. </small><DiagnosticCTA/></div></div><aside className="rv-nfc-preview" data-reveal><img src="/mockups/cartao-nfc.webp" alt="Illustrative Google review NFC card beside a phone" width="1536" height="1024" loading="lazy" decoding="async"/><p className="rv-label"> Annual plan bonus </p><h3> Make inviting customers to leave a review easier. </h3><p> Your customer holds a compatible phone near the NFC card to access your business’s Google review link. </p><p className="rv-nfc-region"><strong>The NFC card is available only to clients in Brazil.</strong></p><p className="rv-demo-note"> Illustrative card design. The review is written by the customer. </p></aside></div></div></section>
<section className="rv-section rv-dark" data-reveal><div className="shell"><p className="rv-label"> Ongoing care </p><h2> The website goes live. <em> The work continues. </em></h2><p className="rv-intro"> Publishing the website is the first step. We then monitor the Google Business Profile when eligible, keep the website running and up to date, check indexing and make SEO improvements within the contracted scope. The annual plan includes this care for 12 months. </p></div></section>
<section className="rv-section" data-reveal><div className="shell"><div className="rv-heading"><div><p className="rv-label"> Website portfolio </p><h2> Websites built <em>  by Ravyt. </em></h2><p className="rv-portfolio-intro"> Conceptual demonstrations and published websites, presented in motion. </p></div><Link href="/en/cases"> Explore the projects ↗ </Link></div><Cases/></div></section>
<section className="rv-section rv-dark" id="sobre" data-reveal><div className="shell"><p className="rv-label"> Who looks after the structure </p><h2> Search and experience. <br/><em> In the same direction. </em></h2><Team/><Link className="rv-text-link" href="/en/sobre"> Meet Ravyt → </Link></div></section>
<section className="rv-section" data-reveal><div className="shell rv-split"><div><p className="rv-label"> Before you decide </p><h2> Good questions. <br/><em> Clear answers. </em></h2></div><FAQ/></div></section>
<section className="rv-final" data-reveal><div className="shell"><p className="rv-label"> Your next step </p><h2> Your next customers are already searching on Google. </h2><p> Let’s prepare your business to be found by them. </p><DiagnosticCTA/></div></section>
</main><BlogFooter/></>}
