export const services = [
 {slug:'seo',name:'SEO',title:"Ceux qui recherchent votre solution peuvent-ils vous trouver ?",description:"SEO stratégique pour rapprocher votre entreprise de ceux qui recherchent déjà ce qu’elle propose.",detail:"Apparaître par votre nom est un début. L’opportunité consiste à être trouvé par le service, la question et le besoin qui conduisent quelqu’un à acheter.",items:["Recherche d’intention de recherche et de concurrence","Architecture et contenu des pages de services","SEO technique, indexation et suivi"]},
 {slug:'google-meu-negocio',name:"Présence locale",title:"Proche du client. Présent au moment du choix.",description:"Profil d’entreprise Google et SEO local pour les entreprises qui doivent être trouvées sur Google et Maps.",detail:"Votre Profil d’entreprise Google — anciennement Google My Business — peut être le premier contact avec votre entreprise. Les services, horaires et avis doivent raconter la même histoire.",items:["Analyse d’éligibilité et configuration du profil","Catégories, services et informations cohérents","Conseils pour les avis et suivi local"]},
 {slug:'sites',name:"Sites stratégiques",title:"Après le clic, la décision commence.",description:"Sites avec UX/UI, rédaction et SEO technique pour transformer la découverte en compréhension, confiance et contact.",detail:"Votre site explique-t-il ce que vous résolvez, pour qui et quelle est la prochaine étape ? Nous construisons ce parcours avec un contenu clair, une bonne expérience mobile et une structure évolutive.",items:["Architecture, UX/UI et textes orientés vers la décision","Développement adaptatif, accessibilité et performance","Formulaires, WhatsApp et mesure selon le périmètre"]}
];
export const projects = [
 {name:'Miraúna Mobiliário',type:"Démonstration conceptuelle",slug:'mirauna',text:"Vitrine de mobilier avec composition éditoriale et mise en valeur des espaces."},
 {name:'Vértice Norte Engenharia',type:"Démonstration conceptuelle",slug:'moreira',text:"Présentation d’ingénierie avec typographie marquante et navigation par spécialités.",nicheHref:"/fr/sites-para-empresas-de-engenharia",nicheLabel:"Sites pour les entreprises d’ingénierie"},
 {name:'Nina Valença Arquitetura',type:"Démonstration conceptuelle",slug:'nina',text:"Portfolio d’architecture avec de grandes images et transitions entre sections.",nicheHref:"/fr/sites-para-escritorios-de-arquitetura",nicheLabel:"Sites pour les cabinets d’architecture"},
 {name:'Lumea Planejados',type:"Démonstration conceptuelle",slug:'lumea',text:"Expérience de meubles sur mesure mettant les espaces en valeur.",nicheHref:"/fr/sites-para-moveis-planejados",nicheLabel:"Sites pour les entreprises de meubles sur mesure"},
 {name:'Arvona Home Center',type:"Démonstration conceptuelle",slug:'arvona',text:"Catalogue visuel pour présenter les catégories et faciliter la découverte."},
 {name:'Serra Norte Distribuição',type:"Démonstration conceptuelle",slug:'serra',text:"Site de distribution avec communication directe et hiérarchie des produits."},
 {name:'CEREST Tianguá',type:"Site publié",slug:'cerest',text:"Informations institutionnelles organisées pour faciliter l’accès aux services."},
 {name:'Capoeira Haute-Savoie',type:"Site publié",slug:'capoeira',text:"Présentation de l’école, de sa pratique et des parcours pour les nouveaux élèves."}
];
export const questions = [
 ["Pourquoi la maintenance est-elle continue ?","Parce que le travail continue après la publication : maintenance et mises à jour du site, support, informations du Profil d’entreprise Google et optimisations SEO."],
 ["Le site m’appartient-il ?","Les conditions de titularité, d’accès et d’éventuelle résiliation seront présentées dans la proposition avant la signature."],
 ["Le domaine et l’hébergement sont-ils inclus ?","Oui. Domaine et hébergement font partie du forfait annuel Google + Site + SEO. Le forfait annuel unique coûte R$ 597,00, payable par Pix, carte ou boleto. Il comprend l’installation et une carte NFC pour les avis Google en bonus. Les conditions précises sont indiquées dans la proposition."],
 ["Que fait Ravyt chaque mois ?","Nous suivons et améliorons le Profil d’entreprise Google, maintenons le site, fournissons le support et travaillons la structure et les optimisations SEO selon le périmètre convenu."],
 ["Quand puis-je constater des progrès sur Google ?","Cela dépend du marché, de la concurrence, de la localisation et de l’historique de l’entreprise. Il n’existe ni délai universel ni garantie de résultat précis."],
 ["Dois-je déjà avoir un Profil d’entreprise Google ?","Non. Nous évaluons la situation et structurons ou optimisons le profil selon l’éligibilité et les besoins de l’entreprise."],
 ["Le service garantit-il la première position sur Google ?","Non. Aucune position précise ne peut être garantie. Nous travaillons à améliorer la structure et la présence numérique de l’entreprise."],
 ["Puis-je me rétracter dans les 7 premiers jours ?","Oui. Avec le forfait annuel, vous disposez de 7 jours pour vous rétracter. Le contrat complet est envoyé avant le paiement."],
 ["Combien coûte le service et comment est-il facturé ?","Le forfait annuel unique coûte R$ 597,00, payable par Pix, carte ou boleto, et comprend une carte NFC pour les avis Google en bonus. Vous disposez de 7 jours pour vous rétracter. Les autres conditions sont envoyées dans le contrat avant le paiement."]
];
